### ISSUE TITLE
Netlify deploy preview for PRs

### ISSUE THREAD

**Issue by jayhesselberth** [r-lib/pkgdown#1057]
Once we're using Github Actions, would be nice to do a site build and netlify deploy preview for each PR.

cc @maxheld83

**Comment by hadley** [comment]
I think we're unlikely to do that here since the easiest workflow is to use github pages, and there's no way to do per-PR deploys. But @jimhester might be able to whip up an example elsewhere.

**Comment by maelle** [comment]
FWIW I have set up workflows (using r-lib/actions &co 🙂) with a bookdown Netlify preview per PR but skipped for PRs from forks since preview deploys need access to the repo Netlify secrets.

Example https://github.com/ropenscilabs/statistical-software-peer-review/blob/master/.github/workflows/pr.yml
