### ISSUE TITLE
Add table of contents when rendering CONTRIBUTING.md?

### ISSUE THREAD

**Issue by maelle** [r-lib/pkgdown#1062]
Many contributing guides have several sections, e.g. https://pkgdown.r-lib.org/dev/CONTRIBUTING.html It'd be nice if the contributing guide were rendered using a similar template as articles, to have the TOC on the right.

I'm not too pandoc-savvy, I saw that there's a `--toc` option, and I could explore this + the `build_article()` function more if there's interest in having a TOC for contributing guides.

**Comment by maelle** [comment]
It seems Markdown files are rendered using `rmarkdown::pandoc_convert()`, so the workflow seems quite different from Rmd rendering. 🤔

**Comment by hadley** [comment]
I thought that this might just be a matter of passing `--toc` to pandoc, but that option only works with `--standalone`.

So I think probably the way to tackle the problem is make a function that takes a string containing html then use an xpath expression extract the `<h2>`s and use them to construct a TOC. `render_md()` would then call this function and insert it's result into the appropriate template variable.

**Comment by hadley** [comment]
Oh, and the `title-body` template needs adjusting to also include a side bar

**Comment by hadley** [comment]
@jayhesselberth could you take a look at this one? I think it might be easier to do now with bootstrap-toc
