### ISSUE TITLE
Auto-linking infix operators from in Changelog

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/pkgdown#1082]
Redirecting from https://github.com/Rdatatable/data.table/pull/3677

`pkgdown` is good at matching `foo()` in `NEWS` to link to `?foo` in the reference section, but it appears to miss infix operators like `%foo%` --> ``?`%foo%``.

**Comment by jayhesselberth** [comment]
I had a look and it's a little tricky because single backticks are used for two purposes in this case: marking code in markdown, and parsing infix operators in R.

So when you write `` `%foo%` `` in markdown, it gets translated to `<code>%foo%</code>`, which lacks the backticks, which are required for R to parse correctly.

If you use double backticks in markdown (``` `` ?`%foo%` `` ```), then help for `%foo%` is linked correctly. But a bare function link does not work (``` `` `%foo%` `` ```) (missing the `?`), and it would be annoying to use double backticks everywhere anyway.

I think we'd have to modify the HTML tweaking code to check whether `<code>%foo%</code>` was a backticked infix operator (in the markdown version) and then link it as if it were.

**Comment by MichaelChirico** [comment]
I don't think I follow the `pkgdown` internals well enough to follow exactly, could you help to point to the code that's driving this?

`grep`ping for `<code>%[^%]*%</code>` would seem to be pretty straightforward, so there must be a gap in understanding when/how the reference linking is applied
