### ISSUE TITLE
LaTeX equations in `README` not getting rendered properly 

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/pkgdown#1150]
Since I updated my `pkgdown` to `1.4.0`, I have been having issues with how math equations and symbols from `README.Rmd` are getting rendered on `Home` page of `pkgdown` website for my package. 

`REAMDE`: https://github.com/IndrajeetPatil/ggstatsplot/blob/master/README.md
`Website`: https://indrajeetpatil.github.io/ggstatsplot/

Here are a few examples of what the `README` output looks like and how it is rendered by `pkgdown`:

- Example 1

**README** output

![image](https://user-images.githubusercontent.com/11330453/65268429-6bc03480-db17-11e9-9d50-0b1b60a8b2e0.png)

**pkgdown** output

![image](https://user-images.githubusercontent.com/11330453/65268092-b3928c00-db16-11e9-81f5-e2deb5f5d74b.png)

- Example 2

**README** output

![image](https://user-images.githubusercontent.com/11330453/65268475-85617c00-db17-11e9-8a93-008861aee063.png)

**pkgdown** output

![image](https://user-images.githubusercontent.com/11330453/65268246-09673400-db17-11e9-952c-8a7a4aa4894d.png)

Etc.

**Comment by Bisaloo** [comment]
I can reproduce on Chromium but it looks fine on Firefox. Maybe this can help pinpoint the source of this issue.

**Comment by IndrajeetPatil** [comment]
@jayhesselberth Any possibility of working on fixing this issue any time soon? 
I have had an ugly homepage for my `pkgdown` website for a few months now. I'd really appreciate any help in fixing this issue. Thanks.

**Comment by jayhesselberth** [comment]
I also just checked and can confirm the page is malformed on chrome but looks fine on firefox. 

I wonder if it's an issue with Mathjax. The most recent [commit](https://github.com/r-lib/pkgdown/commit/59d3618ffd094f56816556c948175f754a597a47#diff-92c240f61585a96bd0bed2040d39d8a9L67-L69) that modifies the Mathjax library brings in an extra JS library. I don't know enough about how Mathjax works to make a prediction about whether this is the issue, but could you delete each one of those from your site locally and confirm whether it fixes the issue? Or revert to the older Mathjax library code?

**Comment by hadley** [comment]
@IndrajeetPatil if you want help, you should start by creating a minimal reprex package that illustrates the problem. But this issue appears to only affect you, so I think is low priority.

**Comment by IndrajeetPatil** [comment]
@jayhesselberth Thanks for the suggestion. Will try to do that.

While exploring some documentation on `mathjax` in `pkgdown` [website](https://pkgdown.r-lib.org/articles/test/mathjax.html), I realized the source of this document is 404: https://github.com/r-lib/pkgdown/blob/master/vignettes/test/mathjax.Rmd

![image](https://user-images.githubusercontent.com/11330453/69817223-71628680-11fa-11ea-9a50-fb6ace3fea7f.png)

**Comment by jayhesselberth** [comment]
Hmm that's a link to old content (wrong version is in the badge). We may need to run clear out old content with `clean_site()` on travis before building new content.

Here's the correct mathjax code:

https://pkgdown.r-lib.org/articles/test/rendering.html

**Comment by IndrajeetPatil** [comment]
@hadley Here is a minimal `reprex` package that demonstrates this issue:
https://github.com/IndrajeetPatil/minimalReprex

- GitHub `README`[ looks](https://github.com/IndrajeetPatil/minimalReprex/blob/master/README.md) fine: 
https://github.com/IndrajeetPatil/minimalReprex/blob/master/README.md
![image](https://user-images.githubusercontent.com/11330453/69874444-47bd6400-12bb-11ea-84bd-cea27a90f7d0.png)

- But `pkgdown` [output](https://indrajeetpatil.github.io/minimalReprex/) is malformed:

![image](https://user-images.githubusercontent.com/11330453/69874464-5572e980-12bb-11ea-80eb-9604121f10b1.png)

**Comment by Bisaloo** [comment]
I see two different issues here:

- Regarding the issue you reported in your first comment, it seems to be stemming from a difference in how Firefox and Chromium are handling `embed src`. Firefox treats it as `img src` while Chromium actually embeds the document. I'm not entirely sure why `embed src` is needed over `img src` here anyways. This is probably due to pandoc itself and they might have a good reason to do so.

- Regarding your comment. It's not a browser display issue but a parsing issue. The source code itself is wrong and this issue is reproducible in both Firefox and Chromium. I'm trying to get rid of MathJax as well for another package of mine and it looks like `rmarkdown` doesn't properly support `--webtex` or `--mathml` options for some outputs. It seems to work fine with for `github_document` but not for `html_document` for example

**Comment by IndrajeetPatil** [comment]
@Bisaloo Thanks for trying to get to the bottom of this issue! I am not an expert in `HTML`/`JS`, so I am a bit out of my depth here, unfortunately.

I _can_ confirm though that I am using the same version of `pandoc` (`2.7.2`) in both my original comment and minimal `reprex` comment. 

I have used `rmarkdown` support for `--webtex` only in `github_document` and can confirm that it works fine but haven't tried `--mathml`.

**Comment by IndrajeetPatil** [comment]
I just updated to `pandoc 2.8.0.1` and can confirm that the same issue still holds.

**Comment by pdhoff** [comment]
I'm also having problems with mathjax rendering for README.md, but the issue seems slightly different. For me, pkgdown renders inline math in my articles (vignettes) just fine, but it doesn't render the same inline math in the README.md file. In an article, the text "$p$-value" gets rendered in html as 

`<span class="math inline">\(p\)</span>-value`

but the same thing from the README.md file gets rendered in index.html as 

$p$-value

Is there a way to have the README.md rendered the same way as the articles?

An example is at 

https://pdhoff.github.io/FABInference/index.html

Thanks for any help or suggestions.

**Comment by Bisaloo** [comment]
@pdhoff, it's because pandoc needs the `tex_math_dollars` and `tex_math_single_backslash` extensions. I just verified it by adding them in my pkgdown fork, and by compiling your page. 

@jayhesselberth, @hadley, do you think these extensions should be added? I'm asking because I'm not familiar enough with the codebase to know if it could have unforeseen consequences in other places.

**Comment by Bisaloo** [comment]
Oh and btw, @IndrajeetPatil, is that the reason you are using `--webtex`? Because this would also solve your issue then (even though the issue with `--webtex` remains a partial mystery to me)

**Comment by jayhesselberth** [comment]
@Bisaloo can you submit a PR with the suggested changes? Then others can confirm whether it works for them, and we can determine whether the changes would have unintended consequences.

I don't know enough about pandoc / mathjax to make a prediction about the effect.

**Comment by pdhoff** [comment]
@Bisaloo Thanks, I understand that `inlineMath: [ ['$','$']` needs to be specified, but I don't know where to put it. How have you done it? Ideally it could be specified in the `override` option in the `build_home` function but maybe it is more complicated than that. 

@jayhesselberth These extensions are apparently already being used when rendering .Rmd files for articles, but for some reason not for README.md's or README.Rmd's.  I'm not sure if the different behavior is a feature or a bug, but  I'm pretty sure (I could check) that this difference in rendering was not present in previous pkgdown versions. 

Thanks for your help and comments.

**Comment by IndrajeetPatil** [comment]
Closing following https://github.com/r-lib/pkgdown/issues/1207#issuecomment-575899270
