### ISSUE TITLE
[bug] \dontrun tags transfomed to `if (FALSE)`

### ISSUE THREAD

**Issue by lbusett** [r-lib/pkgdown#1154]
On pkgdown 1.4.1, the `\dontrun` tags in examples are apparently transformed into `if (FALSE)` statements in the rendered website.  

See for example: 

https://ropensci.github.io/MODIStsp/reference/MODIStsp.html
https://sen2r.ranghetti.info/reference/s2_download.html

Is that by design?

**Comment by hadley** [comment]
Yes.

**Comment by JiscaH** [comment]
Since this feature seems to have been flagged multiple times as a potential bug, is there really no alternative? E.g. printing it as #/dontrun{  analogous with #/donttest?  I'm worried the "if (FALSE)" is confusing for people trying to understand and reproduce an example in the rendered website. 

Otherwise, great package :)

**Comment by jayhesselberth** [comment]
This is by design. `\dontrun{}` tags are converted to `if (FALSE)` so that code copy/pasted from the examples can be executed in a console. You'd have to prefix the whole code block with `#` to achieve the same effect.

**Comment by JiscaH** [comment]
Thanks for the clarification! That does actually make a lot of sense when you put it like that.
