### ISSUE TITLE
pkgdown::build_article throwing pandoc error

### ISSUE THREAD

**Issue by rupertoverall** [r-lib/pkgdown#1163]
Since today, I am getting an error when running pkgdown::build_site()
Specifically, it is not able to correctly locate image resources - although the site built perfectly yesterday before I ran update.packages().
I have tried running pkgdown::build_article() using a minimal Rmd file with an embedded image (below).

The error I get is:
File Rlogo.png not found in resource path
Error : pandoc document conversion failed with error 99
Error: callr subprocess failed: pandoc document conversion failed with error 99

Using an absolute path does not produce the error, but does not include the image.
Using the Rmd format `![](Rlogo.png)` also does not work.

Creating the HTML page using rmarkdown::render() works fine.

____________________________Test_page.Rmd_______________________
```
---
title: "Test"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Test}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Test
This is a test page.
<img src="Rlogo.png"></img>
```

**Comment by cderv** [comment]
I think this is related with an issue in last rmarkdown 📦 version regarding `html_vignette`.
I can reproduce with rmarkdown 1.16 only, that you would have installed in your update process. 
This issue is already fix in rmarkdown dev version.

You can either: 

* downgrade to `rmarkdown` 1.15 : `remotes::install_version("rmarkdown", "1.15")`
* use last dev version : `remotes::install_github("rstudio/rmarkdown")`

This should work. at least in my test it works. 
Please, confirm it. Thank you !

**Comment by rupertoverall** [comment]
I can confirm that both 1.15 and 1.16.1 from github solve the issue for me.
Thank you very much for your help!
