### ISSUE TITLE
Broken syntax for [, [[, [<-, …

### ISSUE THREAD

**Issue by flying-sheep** [r-lib/pkgdown#1175]
The Rd code for

```rd
\S4method{[}{DPT,index,index,logicalOrMissing}(x, i, j, ..., drop = TRUE)
```

is converted into

```r
# S4 method for DPT,index,index,logicalOrMissing
[(x, i, j, ..., drop = TRUE)
```

instead of

```r
# S4 method for DPT,index,index,logicalOrMissing
x[i, j, ..., drop = TRUE]
```

**Comment by hadley** [comment]
Reprex:

``` r
library(pkgdown)
rd2html("\\S4method{[}{foo}(x, i, ...)")
#> [1] "# S4 method for foo" "[(x, i, ...)"
```

<sup>Created on 2020-03-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
To resolve this, I think `as_data.tag_usage()` needs to switch to using `parse_usage(x)`. We'd also need a new function that generates user friendly usage statements from `parse_usage()` output. 

I have a vague worry that this isn't 100% general because it's possible for `\usage{}` to contain statements other than valid R code (e.g. you might include additional comments). This is unlikely to affect packages using roxygen2 (since the autogenerated usages have a much more limited form) but it may affect older R packages.

**Comment by hadley** [comment]
I was also thinking of the old syntax that allowed multiple usage calls: https://github.com/wch/r-source/blob/tags/R-2-3-0/src/library/graphics/man/abline.Rd. This went away in R 2.4.0 almost 16 years ago 😬

**Comment by hadley** [comment]
Ah the big challenge is that going via `parse_usage()` is that the conversion to an R expression loses whitespace so that we'd lose the formatting of the usage from the Rd file. 

At this point I don't see anyway to easily resolve this situation so I'm going to put aside in the hope that a simple solution will reveal itself in the future.

**Comment by hadley** [comment]
I'm closing this issue in recognition of the fact it's 2 years old and I've despite a couple of attempts I've made no progressive on solving it. Given that it seems to affect few people, I think unfortunately we don't have the development resources to spend on this problem.
