### ISSUE TITLE
Store platform and R version used for site build

### ISSUE THREAD

**Issue by jayhesselberth** [r-lib/pkgdown#1286]
Store in pkgdown.yml site config file.

**Comment by hadley** [comment]
What are you thinking here? It doesn't seem that useful to record just the R version and OS, unless we also record all package versions. I don't think #1282 is sufficient justification since that appears to be a very unusual problem.

**Comment by jayhesselberth** [comment]
Knowing the platform (everyone was using Windows) would have been helpful for #1282.

A full `session_info()` dump in `pkgdown.yml` is extreme, but it's only a few extra KB in a file that is rarely served.

**Comment by hadley** [comment]
I just think that's such a weird and specific issue it's not worth generalising potential solutions on that basis. Even if we had recorded the platform, I wouldn't have trusted that was the difference until verifying myself because it's so unlikely that the platform would have affected syntax highlightin.g
