### ISSUE TITLE
Links to rdrr.io lead to advertisements

### ISSUE THREAD

**Issue by jranke** [r-lib/pkgdown#1321]
I would rather not be distracted by ads when I want to look up the documentation of a function e.g. in base R or in one of the recommended packages.

How about linking to stat.ethz.ch, e.g.

https://stat.ethz.ch/R-manual/R-devel/library/base/html/matrix.html

Of course it would be nice to have a more featureful html documentation site, at least for base and recommended packages. Would this be something for the R foundation? Is such a documentation site planned for rhub.io?

**Comment by jayhesselberth** [comment]
I don't see advertisements on rdrr.io. Can you provide an example?

**Comment by jranke** [comment]
![image](https://user-images.githubusercontent.com/3621037/81711373-e60d4280-9473-11ea-91ad-d1b670df1aa2.png)

**Comment by jranke** [comment]
Are you using an adblocker?

**Comment by jayhesselberth** [comment]
Yes, I had an ad blocker on. I agree those ads annoying, but I assume they pay for the site.

**Comment by jranke** [comment]
OK, you have a point there. I would still prefer a site that is free free of ads. I believe there are plenty of hosting capacities on the CRAN servers... I guess loading it all on stat.ethz.ch would not be the best solution...

**Comment by jranke** [comment]
And I assume they do not pay pkgdown developers for linking to their site :)

**Comment by maxheld83** [comment]
This is going to be a difficult conversation, and I don't want to make it bigger, but just to add the opposing viewpoint:

While I agree in principle that e.g. https://stat.ethz.ch/R-manual/R-devel/library/base/html/matrix.html would be preferable, but I *always* use e.g. https://rdrr.io/r/base/matrix.html when there's no pkgdown site, because I just find it so much easier to read and so much better designed.

https://stat.ethz.ch/R-manual/R-devel/library/base/html/matrix.html has no syntax highlighting, crosslinks, navbars ... and pretty bad design.

So for pragmatic reasons, I'd be in favor of maintaining the current links to rdrr.io.

**Comment by jranke** [comment]
Thanks for chiming in  @maxheld83! I do not see that this will be a difficult conversation, just the solution is difficult. I agree the standard R html help is disappointing for people used to the nice pkgdown layout and features. But in my opinion linking to a site with ads is worse.

**Comment by hadley** [comment]
Thanks for bringing this issue to our attention. At this time, I don't think the tradeoff of removing ads in return for decreased functionality is sufficient for us to make a change.

**Comment by jayhesselberth** [comment]
@hadley sh/could the remote documentation url be a configurable setting in downlit?

**Comment by hadley** [comment]
I think that would be a reasonable, but I'd want it to be accompanied by a PR.
