### ISSUE TITLE
Highlighting for TOML

### ISSUE THREAD

**Issue by maelle** [r-lib/pkgdown#1358]
Maybe an issue for downlit/hugodown repo instead? At least it's all the same org so the issue is transferrable. :sweat_smile: 

In https://hugodown.r-lib.org/articles/config.html the toml blocks are not highlighted, and more importantly, don't get the copy-paste button.

**Comment by hadley** [comment]
I _think_ that's handled by pandoc? I don't recall that we're doing anything special for code blocks apart from R.

...

Ah yeah, there's no `TOML.xml` directly here: https://github.com/jgm/skylighting/tree/master/skylighting-core/xml. So I think the way to fix it would be to add TOML support to skylighting.

**Comment by maelle** [comment]
For the record, I think it's unlikely it'd happen in skylighting https://github.com/jgm/skylighting/issues/18#issuecomment-332902642

Then there's the Pandoc option for adding a language https://pandoc.org/MANUAL.html#syntax-highlighting but that's probably not worth the effort to let pkgdown users access that :-)

**Comment by cderv** [comment]
@maelle It seems they heard you because now there is one toml.xml https://github.com/jgm/skylighting/blob/master/skylighting-core/xml/toml.xml
they synced with the KDE repo to increase the number of supporting language. 

It is from version 0.10+ so very recent (a month ago) so now yet available into pandoc I believe. But you'll have it in next version I believe.

**Comment by maelle** [comment]
thanks for telling me @cderv, this is great!
