### ISSUE TITLE
Strip `# \dontrun{` from examples when site built with `run_dont_run = TRUE`

### ISSUE THREAD

**Issue by rundel** [r-lib/pkgdown#1403]
When building a pkgdown site with examples using `\dontrun{...}`, I find the inclusion of this text in the final output to be somewhat ugly / distracting. 

Including this text doesn't seem to add anything particularly important for most use cases, and if it is necessary for some it seems like this could be conveyed via alternative formating of the html page (e.g. different background colors or a border box). 

Alternatively,  wrapping these kind of control arguments in a div with an appropriate class would enable someone to hide them via css.

**Comment by hadley** [comment]
Unfortunately it's challenging to do this because of how whitespace is allocated to various bits of the Rd AST. I've spent quite a bit of time trying to do this in the past but have never succeeded. You might try using the experiment and undocumented `@examplesIf` instead: https://github.com/r-lib/pkgdown/pull/1236
