### ISSUE TITLE
Switch to bootstrap 4

### ISSUE THREAD

**Issue by hadley** [r-lib/pkgdown#1409]
* Needed for greater consistency with future releases of shiny, rmarkdown, bookdown etc.
* Probably needs to be opt-in (or definitely needs to be opt-out)
* Use [bootstrap lib](https://rstudio.github.io/bootstraplib/index.html)
* Provide a few customisation parameters (e.g. key colours + font)

**Comment by matthewstrasiotto** [comment]
> * Provide a few customisation parameters (e.g. key colours + font)

Out of curiousity, does such customization exist for the current bootstrap 3 system? 

I was trying to style something using `bg-success` `bg-warning` etc the other day, and noticed that the colors were very low saturation, basically pastel. 

This was okay, but surprised me a little - is this configurable anywhere?

**Comment by hadley** [comment]
@matthewstrasiotto no, there's no customisation built in

**Comment by hadley** [comment]
Start from template in `bookdown::bs4_book()`

**Comment by jeroen** [comment]
Also note bootstrap 5 is getting close to a release: http://getbootstrap.com/

**Comment by hadley** [comment]
I skimmed a few articles about differences between v4 and v5, and I think this is the best summary: https://designmodo.com/bootstrap-5/

**Comment by amirmasoudabdol** [comment]
I would be interested in looking into this. I started my project by adapting bootstrap 4, and considered 5 at some point too, but decided to wait for pkgdown and see how you guys are going to more forward.

In terms of compatibility, bootstrap 4 is very much compatible with 3, the only real issue is the navigation bar which needs to be rewritten. Other than that, in my prototypes, I haven't noticed anything else being broken. I think the jump from 3 to 5 is going to be more challenging, but not terribly difficult.

I might start playing around with bootstrap 5 a bit more, as I'm somewhat warmed up! 😅
