### ISSUE TITLE
Dependency on downlit version

### ISSUE THREAD

**Issue by dmurdoch** [r-lib/pkgdown#1588]
If I install `downlit` from CRAN, `pkgdown` will install but won't work, because the updates I submitted in PR #1548 need argument changes to `downlit::evaluate_and_highlight`.

Strangely, adding a version requirement of `downlit (>= 0.2.1.9000)` still lets `pkgdown` load, even though the CRAN version is only `0.2.1`, so I'm not sure how to fix this.

**Comment by hadley** [comment]
Hmmmm, that is weird — `load_all()` appears to be checking the version but `library()` does not. I have a vague recollection that maybe it's only `install.packages()` that uses the version requirements?

I _think_ it's ok to leave this as is; it should affect relatively few people since you'd need to install dev pkgdown and then CRAN downlit. (And hopefully we'll get releases of both packages out soon, since that's now my current focus)
