### ISSUE TITLE
Add active sidebar nav items + scrollspy?

### ISSUE THREAD

**Issue by apreshill** [r-lib/pkgdown#1642]
Hi @maelle 👋 

I'm not sure if this is related to issue #1641, or if my question is more of a documentation rather than functionality issue, but I'm working with dev pkgdown and finding that I cannot figure out how to apply CSS to the sidebar active nav item anymore. My old CSS doesn't work that worked with CRAN pkgdown, and I tried to use this from the `bs4_book` but that didn't work either:

```
nav[data-toggle="toc"] .nav .nav-link.active > li > a, 
nav[data-toggle="toc"] .nav a.nav-link.active {
	background-color: #eee;
}
```

I can change hover and focus, but active doesn't seem responsive. Thanks!

**Comment by maelle** [comment]
I'll come back to this, thanks again for your patience and bug catching. :pray: :hedgehog: 

https://github.com/r-lib/pkgdown/blob/dff8062d297c001dba0dfaf567bfffdc8ad89f5c/inst/assets/BS4/pkgdown.css#L278-L287

**Comment by maelle** [comment]
@apreshill do you use Bootstrap 4, by the way?

**Comment by apreshill** [comment]
Yes! Sorry more detail- I'm testing this on a personal package right now before I touch quillt, which is my next stop.

Here is a link to my in progress `_pkgdown.yml`:
https://github.com/apreshill/bakeoff/blob/fa210c725e4c6b51ae1e7c86665cf504977c142d/_pkgdown.yml#L9

**Comment by maelle** [comment]
So I think it was both due to the aforementioned issue (the highlighting of the TOC didn't work for the reference page at all) + the active class being on a. https://github.com/apreshill/bakeoff/pull/7

Locally I re-installed pkgdown latest version and built your website. It's very pretty.

![image](https://user-images.githubusercontent.com/8360597/116691087-9ee8cc00-a9ba-11eb-9287-01cb025105eb.png)
