### ISSUE TITLE
Add anchors to reference section headers

### ISSUE THREAD

**Issue by colearendt** [r-lib/pkgdown#1747]
This is most important to me on the "Reference" section headers, i.e. here: https://pkgdown.r-lib.org/reference/index.html

There may be other places, though. In the Changelog?

This is done automatically on the "README," for instance: https://pkgdown.r-lib.org/#in-the-wild

**Comment by klmr** [comment]
You can already link to these headers, since they all have IDs. For instance, in the first link you’ve posted the section headers have the ID `section-‹header slug›`, e.g. https://pkgdown.r-lib.org/reference/index.html#section-templates.

It’s just that, for some reasons, the “anchor link” image isn’t displayed next to the headers on hover specifically on the Reference page. For other pkgdown websites (but not the current ‘pkgdown’ website proper), some other pages (such as vignettes and the “Changelog” page) *also* don’t show anchor link images next to section headers. In those cases that’s due to `<h2>` elements not carrying a `class="hasAnchor"` attribute.

**Comment by colearendt** [comment]
Thanks for the clarification - that's a great distinction. Would it be possible to include such "anchor link" images? Is that something easily customizable by a user?

**Comment by hadley** [comment]
(@colearendt for future reference these are called anchor links)
