### ISSUE TITLE
Recommend/mention the possible use of alerts in vignettes?

### ISSUE THREAD

**Issue by maelle** [r-lib/pkgdown#1765]
I.e. https://bookdown.org/yihui/rmarkdown-cookbook/custom-blocks.html + https://getbootstrap.com/docs/5.1/components/alerts/

Maybe out-of-scope for pkgdown docs themselves. :thinking:

**Comment by hadley** [comment]
And won't necessarily look good in R itself? (since the bs styles won't be there). Either way, I don't think this is a priority right now.

**Comment by doccstat** [comment]
Is it possible that GitHub flavored markdown alert blocks can be added as seen in https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts. Their way is elegant and will look good in R as well since it is just an extension of the quote block.

The request arises when an R package has the alert blocks in `readme.Rmd` and the corresponding `readme.md` generated by `devtools::build_readme()`. The `.md` file is show on GitHub properly but not the `pkgdown` built site.

Example in GitHub readme
<img width="851" alt="image" src="https://github.com/r-lib/pkgdown/assets/38049831/d61173a3-8a06-4d94-b6e1-a0c07bef0397">
Example in pkgdown page
<img width="781" alt="image" src="https://github.com/r-lib/pkgdown/assets/38049831/12a46fe4-91ec-480e-9b89-546853934798">

I didn't find a simple way to automatically un-escape a character, but I have to manually un-escape `[` and `]` and split the line in generated `readme.md`.

**Comment by maelle** [comment]
@doccstat can you please open a new issue rather than commenting on this closed one? This will make issue triage easier. :smile_cat:

**Comment by hadley** [comment]
The problem with supporting this in README is that CRAN also displays README files, and they obviously won't have support for this feature.
