### ISSUE TITLE
Translate "Usage" string

### ISSUE THREAD

**Issue by dieghernan** [r-lib/pkgdown#1908]
Hi,

Related with #1906 , also "Usage" key is not translated as it is hard-coded.

https://github.com/r-lib/pkgdown/blob/efc2feb7d0e6a4aa9791498b7c37560e4f0b2c38/inst/BS5/templates/content-reference-topic.html#L20

**Comment by hadley** [comment]
Ooops, not sure how I missed that.

**Comment by dieghernan** [comment]
Well, I spend also some hours on that and I didn't see it either...

By the way, the tooltip is not translated (see https://dieghernan.github.io/nominatimlite/index.html) thats why I used:

```r
## File: development.R

meta_development <- function(meta, version, bs_version = 3) {
  # Need to re-bind locales here for translation
  local_envvar_pkgdown(meta)
  dir <- system.file("po", package = "pkgdown")
  bindtextdomain("R-pkgdown", dir)

...

```

I am not really sure how the tranlations is implemented (apart of this);
https://github.com/r-lib/pkgdown/blob/6a412e3a9d2d12d43e6b24eb25b97633ec350cda/R/pkgdown.R#L26-L32

But maybe the locale is set after the first call to `development` (just guessing)?

Thanks

**Comment by hadley** [comment]
The problem is that `meta_development()` is called in `as_pkgdown()` which happens before `local_envvar_pkgdown()` (since `local_envvar_pkgdown()` need the `lang` from the `_pkgdown.yml`). Probably the easiest way to break this cycle is to compute `version_tooltip` at render time, not in `as.pkgdown()`.
