### ISSUE TITLE
Widget + Interactivity (TOC, copy-paste button)

### ISSUE THREAD

**Issue by SESjo** [r-lib/pkgdown#1929]
I've noticed two issues when using widgets (I've only tested DT and leaflet) in a vignette:
- the TOC seems "less" interactive (showing only the first level and losing the highlighted section)
- I also lose the copy-paste "button" that should pop-up on the top right of every piece of code in the vignette, when moving the mouse over.

Normal page: [https://sesjo.github.io/simple-package/articles/control.html](https://sesjo.github.io/simple-package/articles/control.html)
Page with DT widget: [https://sesjo.github.io/simple-package/articles/with_widget_DT.html](https://sesjo.github.io/simple-package/articles/with_widget_DT.html)
Page with leaflet widget: [https://sesjo.github.io/simple-package/articles/with_widget_leaflet.html](https://sesjo.github.io/simple-package/articles/with_widget_leaflet.html)
Source code: [https://github.com/SESjo/simple-package/tree/main/vignettes](https://github.com/SESjo/simple-package/tree/main/vignettes)

**Comment by gadenbuie** [comment]
I'm fairly certain the crux of the problem is that both pkgdown and DT/leaflet load jQuery, which causes problems.

@hadley One option might be to update `pkgdown_print.htmlwidgets()` to remove jQuery from the htmlwidget dependencies. How would you handle version differences? We could

1. Always remove the dependency so pkgdown doesn't break, with a warning if there's a major version mismatch
2. Only remove the dep if the major (or major + minor) version matches, with a warning when jQuery is going to be loaded twice
3. Opt in dep removal via an option set in the article/vignette, e.g. `pkgdown.htmlwidgets_remove_jquery` (or another better name)

**Comment by hadley** [comment]
Option 1 sounds good to me.
