### ISSUE TITLE
Figure path in Readme gets relocated

### ISSUE THREAD

**Issue by mrcaseb** [r-lib/pkgdown#1943]
It seems like this test is testing that figure paths to `man/figures` are relocated to `reference/figures` which breaks any figure in the Readme that links to `man/figures`
https://github.com/r-lib/pkgdown/blob/9b17511675bc33fd14715a84231aee38f1261edb/tests/testthat/test-build-articles.R#L8-L28

I don't know how to provide a reprex for this so I link to the Readme.md of my pkgdown site and the corresponding html.
The readme links to `man/figures` 
https://github.com/nflverse/nflfastR/blob/e5928b49622469d183d19d6a9dbc7399bf163f30/README.md?plain=1#L106
while the actual html links to `reference/figures`
https://github.com/nflverse/nflfastR/blob/c2fd9e9c3a2cd987a5f973cefca551c9773731d7/index.html#L190

**Comment by hadley** [comment]
Yes, that's where figures go; there's no `man` directory on the website (just in the package).

Instead of:

````
```{r echo=FALSE, fig.align='center', fig.cap='', out.width='100%'}
knitr::include_graphics('https://github.com/nflverse/nflfastR/raw/master/man/figures/readme-epa-model-1.png')
```
````

You need

````
```{r echo=FALSE, fig.align='center', fig.cap='', out.width='100%'}
knitr::include_graphics('man/figures/readme-epa-model-1.png')
```
````

That will work locally, and will be automatically relocated on your site.

**Comment by wkdavis** [comment]
@hadley If you look at this example here: https://github.com/wkdavis/rpkgreprex/runs/4408853389?check_suite_focus=true, at the very end of the "Create Website" step you can see this warning message:

```
Warning message:
Missing images in 'README.md': 'reference/figures/README-pressure-1.png'
ℹ pkgdown can only use images in 'man/figures' and 'vignettes' 
```

I'm not sure what the purpose of this warning message is, because the images are in `man/figures`, and the website seems to build correctly.

**Comment by mrcaseb** [comment]
> Yes, that's where figures go; there's no `man` directory on the website (just in the package).
> 
> Instead of:
> 
> ```
> ```{r echo=FALSE, fig.align='center', fig.cap='', out.width='100%'}
> knitr::include_graphics('https://github.com/nflverse/nflfastR/raw/master/man/figures/readme-epa-model-1.png')
> ```
> ```
> 
> You need
> 
> ```
> ```{r echo=FALSE, fig.align='center', fig.cap='', out.width='100%'}
> knitr::include_graphics('man/figures/readme-epa-model-1.png')
> ```
> ```
> 
> That will work locally, and will be automatically relocated on your site.

Sorry, my bad. This worked fine. Thanks for the reply!
