### ISSUE TITLE
Possible to suppress building the search index entirely?

### ISSUE THREAD

**Issue by tomsing1** [r-lib/pkgdown#2046]
I am wondering if it is possible to suppress building the search index? It takes quite a bit of time (because I have beefy vignettes).
According to [the manual](https://pkgdown.r-lib.org/articles/search.html) individual pages can be excluded. But is it possible to opt out of indexing entirely? Many thanks for any pointers!

**Comment by jayhesselberth** [comment]
It's not currently possible to completely suppress building the search index. 

Easy enough to supply a user configurable option to suppress the build, but we'd also need to hide the search bar as well.

**Comment by tomsing1** [comment]
Thanks a lot for confirming that I am not overlooking this functionality (for now) @jayhesselberth, much appreciated!

**Comment by hadley** [comment]
Thanks for filing this issue! Unfortunately, since no one else has asked for it (and it's a reasonable amount of work), I don't think it's ever likely to rise to the top of our collective to do lists. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
