### ISSUE TITLE
Prompted to install tidytemplate, but can't do it because it is GitHub only

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/pkgdown#2076]
```r
> pkgdown::build_site()
ℹ The package `tidytemplate` is required.
✖ Would you like to install it?

1: Yes
2: No

Selection: 1
Error: Cannot install packages:
* tidytemplate: Can't find package called tidytemplate.
Type .Last.error.trace to see where the error occurred
```

Eventually occurs right here https://github.com/r-lib/pkgdown/blob/d1a64f28518dc83905c6dc36ce68eeaaa80d3505/R/utils-fs.R#L86

Goes through `as_pkgdown()` -> `find_template_config()` to get there

This is in my `_pkgdown.yml`, of course:

```
template:
  package: tidytemplate
```

**Comment by maelle** [comment]
Depending on your GHA workflow, this could work:

https://github.com/tidyverse/reprex/blob/318363cf7a911010ebb1593765cc21ec207d2d10/DESCRIPTION#L57-L59

**Comment by maelle** [comment]
I experienced this error today (I agree it's annoying!) so was reminded of this.

I wonder whether instead of just `check_installed()` pkgdown should query the info from DESCRIPTION `Config/Needs/website` in case the template package is listed there, and use that to trigger an installation in interactive sessions.

**Comment by hadley** [comment]
It looks like it's going to be a decent amount of work to look up the full package remote from the DESCRIPTION, so I think it's best just to throw a different error here, as @DavisVaughan suggested.
