### ISSUE TITLE
Restore no-pandoc action

### ISSUE THREAD

**Issue by hadley** [r-lib/pkgdown#2078]
But figure out how to make sure that pandoc isn't actually installed.

Might also be worth considering an action with the same version of pandoc that CRAN has.

**Comment by cderv** [comment]
Some context information I can add about that

> But figure out how to make sure that pandoc isn't actually installed.

Pandoc will be installed by **pak** as it is identified as a system requirement for R packages. It will be installed running 
````sh
sudo apt-get install -y pandoc
````
So it should be possible to uninstall using `sudo apt-get --purge remove pandoc`

> Might also be worth considering an action with the same version of pandoc that CRAN has.

If we have the information for sure of which version is used in CRAN builders, I am interested to update also our workflow. I'll follow this issue.

**Comment by hadley** [comment]
@cderv I was going to ask you if you knew which version of pandoc CRAN used 😄

**Comment by cderv** [comment]
Honestly it is still a mystery to me which version is really used during R CMD checks on CRAN. We don't really know for sure and it is possible that this is still pandoc < 2.0.0 version. It is also possible that a different version is used depending on where it is checked. 

I don't know how we retrieve this information for sure.  Would it be possible somehow to a logging message in a package (rmarkdown?) somewhere in the code (in tests ?) so that we run `rmarkdown::find_pandoc()` and write the information in one of the log that we could then look into after CRAN checks ? Just an idea, I don't know enough of CRAN to know what would really be possible and harmless.
