### ISSUE TITLE
Help with external figure in vignette

### ISSUE THREAD

**Issue by ramiromagno** [r-lib/pkgdown#2088]
Hi pkgdown team,

I need a hand getting my graphics showing up in the HTML generated by pkgdown via GitHub actions.

pkgdown version is 1.6.1.

I have this image I am including in my article but it is not showing up in the rendered HTML online. It does work locally with `pkgdown::build_site()` or if I knit it.

![snap](https://user-images.githubusercontent.com/19862384/168432991-881f00a0-8eca-4eda-b721-2d97fd155e8c.png)

This is the source: https://github.com/maialab/agvgd/blob/HEAD/vignettes/articles/lee2010.Rmd.

Briefly, the approach I am using is by setting the option `resource_files` in the YAML:

```
---
title: "Missense Variations in the BRCT Domain of BRCA1"
resource_files:
  - '../../man/figures/lee2010_fig03.png'
bibliography: "`r system.file('references.bib', package = 'agvgd')`"
csl: "`r system.file('nature.csl', package = 'agvgd')`"
---
```

and then use `knitr::include_graphics()`:

```{r  out.width = "90%", echo=FALSE}
knitr::include_graphics('../../man/figures/lee2010_fig03.png') 
```

I had used this approach before in other packages and it worked fine, e.g. https://github.com/maialab/quincunx/blob/master/vignettes/pgs-construction-process.Rmd.

I've seen https://github.com/r-lib/pkgdown/issues/1943 but I don't think it helps in my case.

**Comment by dmurdoch** [comment]
In the displayed copy of your article, the link becomes `../../reference/figures/lee2010_fig03.png`, but in order to work, it should be `../reference/figures/lee2010_fig03.png`.  So as a workaround, maybe you could change the link to use one less `..` in one or both of the places you use the path.

Or maybe putting the article in the top level location of `vignettes` instead of putting it in `vignettes/articles` would do it.  That's the normal place for a vignette in an R package.  Then you'd want one less `..` in both locations.

**Comment by ramiromagno** [comment]
Okay, thanks.
