### ISSUE TITLE
Support for "target" in navbar components.

### ISSUE THREAD

**Issue by JSchoenbachler** [r-lib/pkgdown#2089]
Hey team, I was wondering if there could be a way to allow for the `target` tag to be specified on Navbar components?

Our use case is that we want to include a link to our Lab's website in the navbar that opens in a new tab (by using `target=_blank`.

**Comment by JSchoenbachler** [comment]
Let me know if you want me to create a PR, or if anything else is needed for this to be a sufficient implementation.

**Comment by JSchoenbachler** [comment]
@maelle just pinging to see if I can get a quick answer on if I approached this correctly and can make a PR!

**Comment by JSchoenbachler** [comment]
@krlmlr Another ping just to see if this is an easy thing!

**Comment by maelle** [comment]
@JSchoenbachler Thank you! You can open a PR as I see you've already made edits anyway. 
I can't say when it'll be reviewed as activities in r-lib repos tend to happen in bursts. Thanks for your patience.

 In general it's recommended to start PRs not from the main branch but from another branch. See e.g. https://happygitwithr.com/fork-and-clone.html#dont-touch-master As the edits you've made are small you might want to save them somewhere else, then start fresh in another branch so your fork's main branch is the same as the current r-lib/pkgdown main branch. To start PRs, usethis helpers are most useful, see https://usethis.r-lib.org/articles/pr-functions.html

Noting that this issue is sort of related to #1630
