### ISSUE TITLE
Size of package logo in website README 

### ISSUE THREAD

**Issue by harshkrishna17** [r-lib/pkgdown#2159]
Hi! I'm struggling with trying to change the size of the package logo in the home page of the pkgdown website. Using this line below:

```
# ggshakeR <img src="man/figures/logo.png" align="right" height="130"/>
```

I am able to change the size of the logo on github, but there seems to be no change in the logo size in the home page of the website after running `build_site()`. Is there any way to change the above? Thanks!

**Comment by dmurdoch** [comment]
You need to set the style property, not the `height`.  See https://stackoverflow.com/a/71205146/2554330 .

**Comment by harshkrishna17** [comment]
I have been trying to implement the fix shown in the answer but unfortunately it is not working. There is a change in the github README, but no change in the home page of the website

**Comment by dmurdoch** [comment]
I tried those two suggestions, and the second one worked.   The logo has class `"logo"`, so you can modify it by adding this code to the `pkgdown/extra.css` file:

```
.template-home img.logo, img.logo {
  height: 200px;
  width: 178px;
}
```

You need the `.template-home` part because some of the standard code modifies the size on the home page specifically.
If you only want this change to happen there, not on every page, then leave off the second selector, i.e. use


```
.template-home img.logo {
  height: 200px;
  width: 178px;
}
```

This change will fail if `pkgdown` ever changes the class of the logo.  It also appears to fail sometimes because the `docs/index.html` page isn't necessarily going to be rebuilt if you only make a change to `pkgdown/extra.css`; delete everything before rebuilding to be sure.

**Comment by harshkrishna17** [comment]
It works! Thank you so much for the help!
