### ISSUE TITLE
Add support for pretty URLs (hide .html extension)

### ISSUE THREAD

**Issue by rempsyc** [r-lib/pkgdown#2173]
Hugo uses pretty URLs per default, and thus hides the `.html` extensions. Does `pkgdown` have any documented way to do this? If not, is that a feature you would consider implementing?

I tried adding `permalink: pretty` to the `_pkgdown.yml` file (based on this [StackOverflow answer](https://stackoverflow.com/questions/21244910/remove-html-extension-from-github-pages)), but it didn't work. I hope I haven't missed an obvious way to do this.

**Comment by maelle** [comment]
Just keeping track of the equivalent Quarto issue https://github.com/quarto-dev/quarto-cli/issues/2065 in case imitation is possible :smile_cat:

**Comment by hadley** [comment]
We haven't made any progress on this in almost two years, and because it's going to require a bunch of work (since it will affect just about every internal link we generate) and has a relatively small payoff, I'm closing this issue in recognition it's unlikely to ever rise to the top of our to do list.  Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
