### ISSUE TITLE
YAML template params documentation

### ISSUE THREAD

**Issue by igordot** [r-lib/pkgdown#2182]
I am trying to understand the `_pkgdown.yml` `template` field. Specifically, when is it necessary to use `params`?

In the [docs](https://pkgdown.r-lib.org/reference/build_site.html?q=params#template), there are a few examples, such as:

```
template:
  params:
    google_site_verification: _nn6ile-a6x6lctOW
```

```
template:
  trailing_slash_redirect: true
```

The behavior also seems to change over time. With BS3, `bootswatch` had to go under `params`, but not with BS5. Is the proper usage with all the possible fields documented somewhere?

**Comment by hadley** [comment]
I don't think there's a lot of rhyme or reason here, and it's just a matter of do what the docs tell you 😄

**Comment by igordot** [comment]
That is reassuring to hear.

You may have missed the second part of the question. Are all the possible fields documented somewhere on a single page?

**Comment by hadley** [comment]
No, they're not, because I don't think that's useful. (i.e. people aren't usually searching for "what are all the options" they're searching for how to do a specific thing).

**Comment by hadley** [comment]
Yeah, I get that, but the fields of `params` are not very often needed and I have higher priority tasks to work on. I don't think this will ever naturally float to the top of my to do list. (And I don't think it's worth anyone else's time, because they'd need to think carefully how to avoid duplicating the docs)
