### ISSUE TITLE
Support vignette on CRAN but excluded from pkgdown website

### ISSUE THREAD

**Issue by cbailiss** [r-lib/pkgdown#2205]
Feature request:  Allow vignettes to be excluded from the pkgdown website but still present in the R Project, e.g. for CRAN.

Example:  I have two versions of vignette - one is shorter for CRAN (builds in less time to meet CRAN constraints) and a longer more detailed version for the pkgdown website.  Previously I could simply omit vignettes from the _pkgdown.yml file index contents (and a warning would be issued) however now an error is generated.

A couple of ideas:

- A new setting where vignettes to be ignored can be listed.
- A new setting that specifies to raise warnings instead of errors if vignettes are missing from the index.
 
For related discussion see https://github.com/r-lib/pkgdown/issues/2202 and https://github.com/r-lib/pkgdown/issues/2055.

**Comment by cbailiss** [comment]
For related discussion see #2202 and #2055.

**Comment by dbosak01** [comment]
I have a related use case where I have a page that I want on the pkgdown website, but not in the Articles menu.  I have it linking from the top navbar instead.  It is a Frequently Asked Questions page that I think should be visible as soon as the user enters the site.  So I need the page compiled and added to the site, but not included in the Articles list.  I was able to to this on previous versions of pkgdown.  Now it seems difficult or impossible given the new restrictions, which (honestly), I can't understand.  It seems a warning would have been sufficient.

**Comment by keller-mark** [comment]
I have a similar use case as above @dbosak01. Pkgdown site here for reference: https://vitessce.github.io/vitessceR/



I include articles on my site by including them in the `navbar` -> `components` part of the `_pkgdown.yml` configuration https://github.com/vitessce/vitessceR/blob/main/pkgdown/_pkgdown.yml#L14  rather than `articles`. This allows me to create a more custom navbar that separates articles into multiple sections (`Examples` and `Articles`), use sub-headings in the dropdowns, and add a link to an external documentation website.

I now need to pin to pkgdown v2.0.4 because my site does not build in the current version.

**Comment by hadley** [comment]
I'd suggest we handle this the same way as references: if a section has title "internal", we silently drop it.

**Comment by hadley** [comment]
If anyone is still interested in this issue, I'd really appreciate any reviews of the associated PR: https://github.com/r-lib/pkgdown/pull/2497
