### ISSUE TITLE
Navigation menu on the right hand side is missing

### ISSUE THREAD

**Issue by xuyiqing** [r-lib/pkgdown#2208]
The navigation menu on the right-hand-side of articles and other pages (such as a tutorial page) is missing

It was fine before, but it is missing on both chrome and safari. For example, nothing is shown under "On this page"
https://pkgdown.r-lib.org/articles/customise.html

**Comment by dmurdoch** [comment]
I see it there on your sample page when I enable Javascript.

**Comment by xuyiqing** [comment]
Thank you. I've made sure that I enabled Javascript using both Chrome and Safari, but the problem persists. In fact, the problem exists for multiple mac computers (after OS update). 

![Screen Shot 2022-10-05 at 12 27 39 AM](https://user-images.githubusercontent.com/7664920/194004515-94cb0f61-a027-4cf6-b9b9-590d8c66dbce.png)

**Comment by xuyiqing** [comment]
Thank you! Did you manage to fix the problem?

**Comment by GregorDeCillia** [comment]
I currently use https://github.com/r-lib/pkgdown/issues/2207#issuecomment-1268156365 as a workaround and patch all generated html files between rendering an deployment.

```r
# render
pkgdown::build_site()
# patch
source("dev/replace_cdn_links.R")
# deploy
fs::dir_copy("docs", file.path(nginx_root, "/my_package"))
```

This is certainly a bit hacky and I didn't try to integrate this with gh-actions or `pkgdown::deploy_to_branch()` because the deployment for my current package is fortunately just a simple copy operation. However, I'm confident this will be fixed either on the cdn side or by pkgdown in a reasonable timeframe.

I suspect a more robust fix would be to use https://pkgdown.r-lib.org/articles/customise.html#additional-html-and-files

**Comment by maelle** [comment]
The dev version now has the fix suggested by @GregorDeCillia. `devtools::install_github("r-lib/pkgdown")`
