### ISSUE TITLE
Quarto articles?

### ISSUE THREAD

**Issue by ldecicco-USGS** [r-lib/pkgdown#2210]
I write many "vignettes" that I promptly add to the .Rbuildignore. I don't want to send them to CRAN, but love adding helpful articles to the pkgdown site. Any chance that there will be support for quarto articles (not vignettes)?

**Comment by JosiahParry** [comment]
Related to suggestion in https://github.com/r-lib/usethis/issues/1671.

I agree with @ldecicco-USGS :) There are some very nice handy dandy features made avaialble by quarto that I would like in my articles but not vignettes.

**Comment by hadley** [comment]
Quarto is now available on CRAN, so this is moving up the priority list.

**Comment by Tripartio** [comment]
> Quarto is now available on CRAN, so this is moving up the priority list.

@hadley Could you please give us the documentation for how to create Quarto articles with our CRAN packages? Or is it as simple as using `.qmd` files where we used to use `.Rmd`?

**Comment by dmurdoch** [comment]
@Tripartio, see here:  https://github.com/quarto-dev/quarto-cli/discussions/2307

**Comment by Tripartio** [comment]
> @Tripartio, see here: [quarto-dev/quarto-cli#2307](https://github.com/quarto-dev/quarto-cli/discussions/2307)

Thanks! I'll follow that thread, then.

**Comment by DanChaltiel** [comment]
@tripartio also see here: https://github.com/quarto-dev/quarto-r/pull/57
I could not find online documentation, but the procedure is described in `vignette("hello", package = "quarto")`.
I was not able to make real quarto syntax (like tabs) work yet though.

**Comment by hadley** [comment]
I've implemented a first pass at this, which covers the features that seemed most critical to me. Please try it out and let me know what doesn't work!

**Comment by DanChaltiel** [comment]
Hi @hadley, thanks a lot for the feature!
I gave it a try, and it works perfectly on my computer (local) (even `pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)`).
However, I could not manage to make it work on GH actions.
For instance, this is the last run I had:
https://github.com/DanChaltiel/EDCimport/actions/runs/10092641396/job/27907083693#step:7:393
![image](https://github.com/user-attachments/assets/0f9806a3-a700-457f-9e7f-d4d2847511ad)
Here is the workflow: https://github.com/DanChaltiel/EDCimport/actions/runs/10092641396/workflow
I hope I did it correctly, but at least I can say that the error message is not specific enough to let me debug this.
Note that my vignette uses tabsets.min.js to have tabs.

About the vignette, it would be nice to reference a minimal reproducible example so that we could simply grab the vignette .qmd file, test that it runs on our setup, and then incrementally change it to make what we want.

Also, the vignette has a bug where [the formula is not shown properly](https://cloud.r-project.org/web/packages/pkgdown/vignettes/quarto.html#eq-black-scholes):
![image](https://github.com/user-attachments/assets/41331a8e-4b91-4ef8-9080-9255a4bffb24)

**Comment by hadley** [comment]
@DanChaltiel can you please file a new issue?
