### ISSUE TITLE
URL validation

### ISSUE THREAD

**Issue by bkmgit** [r-lib/pkgdown#2216]
It would  be helpful to validate links that are created by pkgdown and issue a warning if a link cannot be found.  Many static site generators do this and it makes site generation and maintenance easier.

**Comment by jayhesselberth** [comment]
This would be easy if we took a dependency on `urlchecker`.

**Comment by hadley** [comment]
Hmmmm, urlchecker does check the `.Rd` and `.Rmd` files, but won't check any links that you've added other ways (e.g. in `_pkgdown.yml`). It's also designed to meet CRANs needs, where you have to resolve redirects. If you're not submitting to CRAN, that's not that useful; and if you are submitting to CRAN, you'll get the checks as part of R CMD check anyway. And we already recommend urlchecker it in our release process (since it's much faster than the built-in method.

So maybe there's nothing to do here?

**Comment by maelle** [comment]
For info, for some (not pkgdown) websites I've seen https://github.com/lycheeverse/lychee-action used

**Comment by hadley** [comment]
I think that adds to my belief that this isn't pkgdown's responsibility since there are other tools that can do it better (urlchecker as part of the release process will tell you the source of the urls, and lychee or similar will be much faster).
