### ISSUE TITLE
`df_print: kable` ignored in `pkgdown` vignette but not locally

### ISSUE THREAD

**Issue by rempsyc** [r-lib/pkgdown#2271]
When knitting the vignette locally, I get the expected result using `df_print: kable` option:

![kable local](https://user-images.githubusercontent.com/13123390/216110167-0b483310-596b-4a28-9945-c1e44ec08af2.png)

But on the rendered `pkgdown` website it seems this option is ignored.

![kable pkgdown](https://user-images.githubusercontent.com/13123390/216114443-11f92d1e-d3a8-43d3-a76a-8da6e70ad422.png)

https://rempsyc.remi-theriault.com/articles/test.html

Is this expected behaviour?

Edit: same behaviour when building site locally with version `2.0.7`, and also version `2.0.0`, so not new behaviour it seems.

**Comment by dmurdoch** [comment]
I think that is expected behaviour, but maybe not ideal behaviour.  The problem is that `pkgdown` replaces your output format spec and most of its arguments with its own special output format, and that one ignores `df_print`.  You could make a feature request to support that argument, or maybe there's already a "proper" way to get it.

Alternatively, you could use this hackish approach.  What `df_print` does is set up `knit_print.data.frame` to do special processing on dataframes.  You can do that yourself using this code:

````
```{r echo = FALSE}
if (pkgdown::in_pkgdown()) {
  knit_print.data.frame <- function(x, ...) {
    knitr::knit_print(knitr::kable(x), ...)
  }
  registerS3method("knit_print", "data.frame",
                   knit_print.data.frame, envir = asNamespace("knitr"))
}
```
````

If you run that chunk at the start of your document you'll get `kable` output in `pkgdown`.  It will likely be formatted slightly differently from the standard method, which is quite complicated.  You can see the one used in R Markdown output using `rmarkdown:::knit_print.data.frame`.

**Comment by rempsyc** [comment]
I see, thanks a lot. I can confirm the workaround works (thanks!).

![kable pkgdown2](https://user-images.githubusercontent.com/13123390/216151243-1ee02d51-5175-412a-a213-e4d6e37d10f3.png)

https://rempsyc.remi-theriault.com/articles/test2.html

That said, I would still like to go ahead with your other suggestion to make it a formal feature request, namely to add `pkgdown` support for the `df_print` argument of `rmarkdown::html_vignette()` so that anyone can benefit from it without having to rely on a workaround.

**Comment by dmurdoch** [comment]
There are some other arguments against the PR I put together besides being not strictly necessary.

- It looks in the existing output formats to find the `df_print` setting.  I don't think there are any other cases where `pkgdown` pays attention to those.
- It would make more sense to put this in a section in the `_pkgdown.yml` file with formatting options for articles, but there's no such section, and I don't know if the `pkgdown` authors want one.

But if you want to follow up on this, you could install the branch I put together:  `remotes::install_github("dmurdoch/pkgdown@df_print")` and try it out.

**Comment by hadley** [comment]
`as_is: true` seems like a good fix to me. Thanks @dmurdoch!
