### ISSUE TITLE
Clarify or fix usage of extra.css

### ISSUE THREAD

**Issue by maelle** [r-lib/pkgdown#2291]
See https://community.rstudio.com/t/custom-pkgdown-theme-from-template-package/161885/8

Should it be possible to use `inst/pkgdown/extra.css` in a template package?

**Comment by hadley** [comment]
I think that thread reveals two issues:

* tidytemplate is confusing because it contains a bunch of files that are only needed for pkgdown 1.0.0 templating. These files are no longer relevant and can be removed, I think.
* Need to be a bit more explicit that the files in `assets` are just copied; you still need to link to them yourself.
* Maybe worth noting explicitly that `extra.css` is not supported.
