### ISSUE TITLE
Unable to build articles with custom rmarkdown output formats

### ISSUE THREAD

**Issue by gadenbuie** [r-lib/pkgdown#2319]
This is a new error that has just popped up recently and that might not be entirely pkgdown's fault (but I haven't been able to track down a smaller reprex).

I have a package (cleanrmd) that provides alternative vignette output formats, which I use for vignettes in several packages.

```yaml
output:
  cleanrmd::html_document_clean:
    theme: new.css
    toc: true
    toc_depth: 2
```

I just started noticing [failures building the pkgdown site](https://github.com/gadenbuie/epoxy/actions/runs/5212903378/jobs/9407132145) with the following error

```
-- RMarkdown error -------------------------------------------------------------------
Error in `map()`:
ℹ In index: 1.
Caused by error in `render_rmarkdown()` at pkgdown/R/build-articles.R:280:2:
! Failed to render RMarkdown
Caused by error:
! in callr subprocess.
Caused by error:
! 'arg' should be one of “default”, “bootstrap”, “cerulean”, “cosmo”, “darkly”, “flatly”, “journal”, “lumen”, “paper”, “readable”, “sandstone”, “simplex”, “spacelab”, “united”, “yeti”
```

I've put together a [repo with a reprex](https://github.com/gadenbuie/pkgdownArticleFormat). Within that repo, building the articles with `pkgdown::build_articles()` will work for the standard `rmarkdown::html_vignette`, but will fail for the custom method.

One (probably very relevant detail) is that removing the `theme` value from `html_document_clean()` by commenting out that line will cause the articles to build correctly. (But IIUC the custom document format should be ignored entirely during the rendering.)

```yaml
output:
  cleanrmd::html_document_clean:
    # theme: new.css
    toc: true
    toc_depth: 2
```

**Comment by gadenbuie** [comment]
My pkgdown CI run [ran correctly about a week ago](https://github.com/gadenbuie/epoxy/actions/runs/5120859126/jobs/9207873231), it seems like the most likely culprit is the recent rmarkdown 2.22 release, but I don't immediately see anything relevant in the [changes between 2.21 and 2.22](https://github.com/rstudio/rmarkdown/compare/v2.21...v2.22).

Here's the diff between session info results: https://www.diffchecker.com/mNuGIyyo/

**Comment by maelle** [comment]
Thanks for the reprex and investigation! 

From a quick thus not thorough exploration, it seems that rmarkdown gets some information from the YAML directly 

https://github.com/rstudio/rmarkdown/blob/58ca4df16a3a5c14f277b1878f9ff5b842fe1306/R/html_resources.R#LL212C3-L212C30 (I found [this commit](https://github.com/rstudio/rmarkdown/commit/58ca4df16a3a5c14f277b1878f9ff5b842fe1306) "promising")

pkgdown passes a special output format ([docs](https://pkgdown.r-lib.org/reference/build_articles.html#output-formats)) but at that stage it seems the one that rmarkdown uses, is the one in the document. `rmarkdown:::resolve_theme("new.css")` gets the error you've noticed.

Maybe it's actually a rmarkdown bug then? :thinking:

**Comment by maelle** [comment]
what I don't get is why the vignette can be rendered from RStudio IDE then?

**Comment by cderv** [comment]
Thanks a lot @maelle 

This is indeed one of the latest fix at https://github.com/rstudio/rmarkdown/pull/2486 that I believe trigger the issue. It is kind of side effect because 

* **pkgdown** runs its own format, and ignoring the YAML 
* but **rmarkdown** will use the YAML frontmatter of a document in its `discover_rmd_resources()` process
* We recently added (or at least tried) to make the process more clever regarding which resource to copy when there is a bslib `theme`
* `cleanrmd::html_document_clean()` has a `theme` argument which does not behave like a `html_document_base()` one, so the **bslib** related functions that was added a while ago to support new feature are not handling this case. 

I'll fix this in **rmarkdown** - not a **pkgdown** issue.

**Comment by maelle** [comment]
Thank _you_ @cderv :pray:

**Comment by cderv** [comment]
> I just need to confirm this as I need to understand why exactly this happens when running in pkgdown and not just with rmarkdown. Something is triggered somehow

I believe this is because **pkgdown** is explictly calling for `find_external_resources()` that the issue is triggered. Otherwise, with usual rendering `discover_rmd_resources()` is not called. So no error shown. 

https://github.com/r-lib/pkgdown/blob/39083f38bbb2de2e1126529392bddf3e6e262ab4/R/rmarkdown.R#L62-L70

`find_external_resources()` will consider the YAML front matter. This is not new https://github.com/rstudio/rmarkdown/blob/10863429024e236389a48f40ab1485620d53d311/R/html_resources.R#L202-L203
```r
  # parse the YAML front matter to discover resources named there
  front_matter <- yaml_front_matter(md_file)
```

And so some of the resources will be discovered and handled based on the YAML of the Rmd file 
```yaml
output:
  cleanrmd::html_document_clean:
    theme: new.css
    toc: true
    toc_depth: 2
```
which I understand pkgdown ignores anyway. It does not seem to have a been an issue until now... So is this an underlying issue to think about ?

We have the why this is triggered. About the actual error with `cleanrmd`, this is because of the above and the fact that `resolve_theme(output_format[["theme"]]))` is checked, but `resolve_theme()` does not handle the case where `theme` can be from another custom format. This is **rmarkdown** improvement for sure.

**Comment by maelle** [comment]
So is any change needed on pkgdown side? Finding external resources is useful :grin:

**Comment by cderv** [comment]
I guess this is working now, as not other issue reported, but I believe you are finding more resources that you need too because finding resources includes the YAML front matter content. But `output` YAML key is not used IIUC. 

Only change to prevent "more files to be copied" (which is probably not an issue most of the time), would be to remove `output` key from YAML as not used at all by **pkgdown**. This would prevent in **rmarkdown** process on it. 

So it depends the **pkgdown** point of view on this.

**Comment by gadenbuie** [comment]
Just to confirm: rstudio/rmarkdown#2493 does indeed solve the problem for me, both in the reprex repo and in my original repo. Thanks @maelle and @cderv!
