### ISSUE TITLE
Feature request: support Github callouts

### ISSUE THREAD

**Issue by etiennebacher** [r-lib/pkgdown#2361]
Hello, this is a feature request related to https://github.com/rstudio/rmarkdown/issues/2523

Github callouts were introduced about 1.5 years ago. They have a specific syntax, like this:

```markdown
> [!NOTE]
> Highlights information that users should take into account, even when skimming.

> [!IMPORTANT]
> Crucial information necessary for users to succeed.

> [!WARNING]
> Critical content demanding immediate user attention due to potential risks.
```
which renders like this on Github:

![image](https://github.com/r-lib/pkgdown/assets/52219252/3cc247b5-066e-4f7d-92b8-423f140070f8)

I would like to use this kind of syntax in the README of some packages, but for now `pkgdown` ignores this syntax. Here's an example repo (https://github.com/etiennebacher/pkgdown.callout) and its website (https://etiennebacher.github.io/pkgdown.callout/).

Is it possible to support this kind of callouts in `pkgdown` websites?

**Comment by hadley** [comment]
Unfortunately, it's going to be difficult to justify supporting these just for the README, when we have other mechanisms for doing callouts in vignettes. However, you might trying to see if these could be supported by RMarkdown/Quarto so that you could use a single syntax and then generate the GitHub specific syntax when generating the README.
