### ISSUE TITLE
math doesn't render in footnotes

### ISSUE THREAD

**Issue by venpopov** [r-lib/pkgdown#2394]
Here's a reproducible example:

```
---
title: "abc"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{abc}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Does this footnote[^footnote-1] work?

[^footnote-1]: $\theta$ is a parameter.
```

When I knit in RStudio, the math in the footnote renders fine:

![image](https://github.com/r-lib/pkgdown/assets/12783882/8f79324c-2b52-4c73-8be5-655b4f8bd98a)

When I render an article/vignette on a pkgdown website, the footnote does not render the math properly:

![image](https://github.com/r-lib/pkgdown/assets/12783882/c0197f2a-7281-4217-8324-32f934d78179)

I also tried this, but the result was the same:

```
---
title: "abc"
output:  bookdown::html_document2
pkgdown:
  as_is: true
vignette: >
  %\VignetteIndexEntry{abc}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


Does this footnote[^footnote-1] work?

[^footnote-1]: $\theta$ is a parameter.
```

Is there a way to get this to work?

**Comment by hadley** [comment]
This is because `tweak_footnotes()` pulls the footnote text out of the DOM and puts it into an attribute where the popup plugin can find it. That means fixing this problem is going to be a lot of work so I think unfortunately my advice is going to be "don't put math in footnotes" 😞 Sorry we couldn't help this time, but I appreciate you using pkgdown and filing the issue, and hopefully we can do better next time you encounter a problem.
