### ISSUE TITLE
Enable starting search with keyboard shortcut

### ISSUE THREAD

**Issue by olivroy** [r-lib/pkgdown#2423]
Like typing `/` to start search. This is enabled on Quarto websites by default

**Comment by hadley** [comment]
Is this something you'd be interested in doing a PR for?

**Comment by olivroy** [comment]
With some guidance, I'd like to.. But I don't know much JavaScript. I would probably not know where to start

**Comment by hadley** [comment]
Since the pkgdown search is a bit simpler than quarto, I think all that `/` would need to do is set the focus to the search field. I also don't know much javascript, so I'd typically ask chatGPT:

> When the user presses `/`, set focus to the seach field (i.e. an input with `type="search"`)

```html
<!DOCTYPE html>
<html>
<head>
  <title>Focus on Search Field</title>
  <script>
    document.addEventListener('keydown', function(event) {
      // Check if the pressed key is '/'
      if (event.key === '/') {
        event.preventDefault();  // Prevent any default action associated with the '/' key
        document.getElementById('searchField').focus();  // Set focus to the search input
      }
    });
  </script>
</head>
<body>

<!-- Search input field -->
<input type="search" id="searchField" placeholder="Search...">

</body>
</html>
```

---

That isn't exactly correct, but it's probably a good idea to add an `id` to the search field anyway. (Although I'd just call it `search` not `searchField`) (Although actually I might call it `pkgdown-search` to ensure it's less likely to conflict with the `id` autogenerated for a vignette heading.

You'd also need to figure out where to actually put the js; I don't know the details off the top of my head, but I do know we have some other random snippets of JS that it could likely join. (I'd also only do this for BS5, not BS3).

**Comment by hadley** [comment]
@olivroy is this something you'd like to work on? If not, I can flag it as an issue for tidyverse developer day, and we can get a newer contributor to have a go.

**Comment by olivroy** [comment]
No, you can mark it as tidy-dev day

**Comment by jayhesselberth** [comment]
At one point, you could type `?` and focus would switch to the search bar. Not sure when that stopped working.
