### ISSUE TITLE
pkgdown doesn't respect `df_print: paged`

### ISSUE THREAD

**Issue by dvg-p4** [r-lib/pkgdown#2432]
This is incredibly inconvenient when trying to, well, create a documentation site that looks nice.

**Comment by hadley** [comment]
What is `df_print: paged`?

**Comment by dvg-p4** [comment]
https://bookdown.org/yihui/rmarkdown/html-document.html#data-frame-printing

**Comment by hadley** [comment]
Unfortunately I think that's going to be hard to support because it requires additional CSS and JS to be added to the page, which is pretty fiddly.   However, I think you'll be able to get something pretty close by using [reactable](https://glin.github.io/reactable/index.html); that should already be supported through the existing support for html widgets.

**Comment by dvg-p4** [comment]
Yeah, I did some fiddling around in a fork, got it to ~90% work, but the CSS involved was pretty hacky (and may have been subtly messing up other formatting.) Thanks for the pointer to `reactable`!

**Comment by dvg-p4** [comment]
@hadley is there any way to get all data.frame output to automatically render as reactable tables (rather than having to manually call `reactable()` around every output?

**Comment by hadley** [comment]
If you can add a custom class, you could also provide `pkgdown_print` method. Otherwise I don't know of a way.

**Comment by dvg-p4** [comment]
I'm trying defining `pkgdown_print.data.frame <- function(x) {reactable::reactable(x)}` but it doesn't seem to be working--perhaps I'm not understanding how `pkgdown_print` is supposed to be used? (There doesn't seem to be much documentation on it.)

**Comment by dvg-p4** [comment]
Oh I see, that's only used for rendering example output in function docs, not for vignettes.
