### ISSUE TITLE
Syntax highlighting for \preformatted code inside custom \section's

### ISSUE THREAD

**Issue by SebKrantz** [r-lib/pkgdown#2617]
The following Rd page uses custom sections: https://sebkrantz.github.io/collapse/reference/fast-statistical-functions.html
Source: https://github.com/SebKrantz/collapse/blob/master/man/fast-statistical-functions.Rd

Thanks for considering!

**Comment by hadley** [comment]
The problem is that we don't really have enough information to know that `\preformatted` is R code. 

We did special case this for the code that roxygen2 generates, so you could mimic that in your own Rd files: https://github.com/rstudio/gt/blob/44603afbe703bf2db3097dae5edadeb9053b58ae/man/gt.Rd#L171-L176

**Comment by SebKrantz** [comment]
Thanks. But it seems it has not worked. I just updated the docs.

 I suppose one way to test that could be to just run `downlit::highlight` and see if it works.

**Comment by hadley** [comment]
It seems to work on https://gt.rstudio.com/reference/gt.html, so you might try figuring out what's different with your site.

**Comment by SebKrantz** [comment]
Yeah my bad, the code hat some issues. It works now.
