### ISSUE TITLE
FR: Add link to dev docs in homepage for development: mode: auto

### ISSUE THREAD

**Issue by olivroy** [r-lib/pkgdown#2628]
Alternative to #1373 or easier solutionÉ

If development mode = "auto",

In the homepage, it would be great to have a link to dev docs?

![image](https://github.com/r-lib/pkgdown/assets/52606734/a0efb1c4-78d2-4c8b-847a-ae88faba2b04)

It would be much simpler than #2072, while still giving a link to development documentation.

Also, for pkgdown, it is not clear to me why the View on CRAN button is only available in the dev version of the website, not released.

![image](https://github.com/r-lib/pkgdown/assets/52606734/83968fb7-b0f6-4a3e-8a01-8a9c5fd371e9)

**Comment by hadley** [comment]
Do you want to have a go at fixing this? I think you can just conditionally add the link if `pkg$development$destination` and `pkg$development$mode == "release"`.

I don't know why the CRAN link didn't appear but I don't think it's related to development mode; I'd guess that `cran_link("pkgdown")` just randomly failed due to an internet issue.

**Comment by olivroy** [comment]
Will take a look! thanks for the tip

**Comment by olivroy** [comment]
I gotta say it feels awkward / out of place after all. So let's not go with this..

![image](https://github.com/r-lib/pkgdown/assets/52606734/dc2b7681-59d6-453f-b91f-a087ea075993)

But it made me learn about pkgdown a little bit more.


Maybe would be better to put under Dev status, but that field is hidden on the released version. So that would require more fiddling.
