### ISSUE TITLE
Tabsets fail if Header 1 used

### ISSUE THREAD

**Issue by al-obrien** [r-lib/pkgdown#2720]
When adding a Header 1, tabsets fail to render in the previewed/deployed pkgdown site. Maybe I am silly and have simply ignored advice never to use a Header 1 in pkgdown articles?

My session (excuse the old R, its legacy code)
- R version: 3.6.3
- pkgdown: 2.0.9

## No header 1 - Tabs work
````r
---
title: "test"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = FALSE,
  comment = "#>"
)
```

## THIS IS A HEADER 2

ASDFASDF


### Tabset with pills {.tabset .tabset-pills}

#### Tab 12

blablablabla

```r
1 + 1
```

Should be "cool" heading below

##### cool

Stuff

#### Tab 2

blop


````
![image](https://github.com/user-attachments/assets/672bb0cc-4574-4465-9402-f3c4ebf54bca)

## Header 1 - Tabs fail
````r
---
title: "test"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = FALSE,
  comment = "#>"
)
```

# THIS IS A HEADER 1

ASDFASDF


### Tabset with pills {.tabset .tabset-pills}

#### Tab 12

blablablabla

```r
1 + 1
```

Should be "cool" heading below

##### cool

Stuff

#### Tab 2

blop


````

![image](https://github.com/user-attachments/assets/6ff136cc-fc63-4345-be90-189a8987264b)

**Comment by hadley** [comment]
It's probably because when you use a h1 in page, pkgdown automatically shifts it, and all other headings, down one level. I think that probably messes up something with the tabset code. But I think the fix is just not to use `<h1>` in pages :) (Because a page should only have a single `<h1>` and that's the page title).
