### ISSUE TITLE
Slashes in markdown urls changed to `%2F`

### ISSUE THREAD

**Issue by andrewmarx** [r-lib/pkgdown#2807]
I have a few prerendered images in my articles that I manually insert in the markdown like so:
```
![](img/coinflipmatrix.svg)
```
This used to be okay and would build into:
```
<img src="img/coinflipmatrix.svg">
```
But under the most recent version of pkgdown, it's replacing the slashes with `%2F`:
```
<img src="img%2Fcoinflipmatrix.svg">
```
Which breaks the link. I don't know if it's actually a pkgdown issue or something else pkgdown uses. If it is pkgdown, I don't know how old my previous version of pkgdown was to narrow down when it started; it may have been very outdated.

**Comment by wlangera** [comment]
Hi

I still have this issue.

**Environment**:

- pkgdown version: 2.1.1
- R version: 4.3.3
- Operating system: Windows

**Description**:

When including images in articles located in `vignettes/articles/`, the generated HTML encodes the `/` characters in the image paths as `%2F`. For example, an image referenced as `figures/bootstrapping.png` results in the following HTML:

```html
<img src="figures%2Fbootstrapping.png" alt="Bootstrap resampling a data cube.">
```


This encoding causes the images not to display correctly on the site.

**Steps to Reproduce**:

1. Place an image in `vignettes/articles/figures/bootstrapping.png`.
2. In an article `.Rmd` file located in `vignettes/articles/`, include the image using Markdown syntax:

 ```markdown
 ![](figures/bootstrapping.png)
 ```

3. Build the site using `pkgdown::build_site()`.
4. Observe that the generated HTML encodes the image path as `figures%2Fbootstrapping.png`.

**Expected Behavior**:

The image path in the generated HTML should retain the `/` characters, resulting in:

```html
<img src="figures/bootstrapping.png" alt="Bootstrap resampling a data cube.">
```

**Additional Information**:

I've attempted to place the images in different directories and reference them using various paths, but the issue persists.

**Comment by Andrew0Hill** [comment]
@wlangera Does this issue still happen for you with pkgdown 2.1.3 (current release)?
