### ISSUE TITLE
Proposal: Handle readme.md and README.md Equally for Cross-Platform Consistency

### ISSUE THREAD

**Issue by fxi** [r-lib/pkgdown#2813]
When publishing to GitHub via an action, the `readme.md` was not rendered as `index.html`, but as `readme.html`. It worked fine locally. It took me a while to understand that `pkgdown` is case-sensitive (as it should be), but macOS and Windows users, by default, use a case-insensitive file system. This can cause some confusion, especially for files where both case notations are accepted, like `readme.md` and `README.md`.

I think `pkgdown` should take this into account.

**Comment by hadley** [comment]
This feels like a risky precedent to me, because if we allow this for `README.md` then people will expect it for `_pkgdown.yml` and lots of other files. It's a bummer that it caused you some confusion, but I don't think modifying the package is going to decrease net confusion.  Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄

**Comment by fxi** [comment]
Absolutely. I just realized this might be the first time I ever used a lowercase `readme.md` or encounter similar issue. Temporary lapse of clarity on my part. Appreciate all the hard work you put into maintaining half the R ecosystem 👍
