### ISSUE TITLE
Pkgdown in the wild

### ISSUE THREAD

**Issue by hadley** [r-lib/pkgdown#401]
Include a list of pkgdown sites + their corresponding github's for people to learn from.

**Comment by GShotwell** [comment]
Also might be worth mentioning that you can search`_pkgdown.yml` on github, which can be very helpful.

**Comment by tjmahr** [comment]
All of the Stan team's R packages have pkgdown site, although we use gh-pages branches for the sites.

* [bayesplot](http://mc-stan.org/bayesplot/index.html) / [github](https://github.com/stan-dev/bayesplot/tree/gh-pages)
* [rstanarm](http://mc-stan.org/rstanarm/index.html) / [github](https://github.com/stan-dev/rstanarm/tree/gh-pages)

These two are probably the best from the team because the first is a plotting package and the second is a modelling package with lots of vignettes.
