### ISSUE TITLE
Markdown within <div> is not rendered in README

### ISSUE THREAD

**Issue by kent37** [r-lib/pkgdown#404]
Markdown-formatted links surrounded by `<div>` tags work fine in articles; in README.md they are rendered as typed rather than converting to links.

For example, in an article this text will render as a link enclosed in a box; in README.md the markdown text for the link is included verbatim.

```
<div class="panel panel-default"><div class="panel-body">
For introductory examples, please see
the [Tutorials](https://mycompany.github.io/myproject/articles/index.html).
</div></div>
```

**Comment by kent37** [comment]
Actually all markdown formatting is ignored within the `<div>` in README.md. See https://kent37.github.io/pkgdown404/index.html for an example - the same source is used in the README and the Article; in the Article it renders correctly, in the README the markdown source is shown.

**Comment by hadley** [comment]
See https://pandoc.org/MANUAL.html#raw-html

So the problem is that the `markdown_strict` format is being used somewhere. 

@gaborcsardi do you have a lead on this?

**Comment by gaborcsardi** [comment]
Actually, I don't why I jumped on this. I think I thought that this is a roxygen md parsing issue, but it is not. Right?

Anyway, AFAIR you cannot use markdown within HTML tags with pandoc, at least not without the `markdown_in_html_blocks` extension. I don't know if that should be turned on for pkgdown.

**Comment by hadley** [comment]
My reading of the docs suggests that pandoc has `markdown_in_html_blocks` on by default so someone just needs to figure out what's suppressing it here. I think this would be a good place for someone from the community to contribute.

**Comment by gaborcsardi** [comment]
@hadley Do you know if it is a pandoc 2.0 option?

**Comment by hadley** [comment]
Oooh, good question.

**Comment by hadley** [comment]
I just tested this an it works just fine for me.  Also note that with pandoc 2.0 you can also use fenced divs.

**Comment by zkamvar** [comment]
Sorry to necro this issue, but I was having the same problem and I found that it is **due to a bug in pandoc's deprecated `markdown_github` when `--section-divs` are used**, which I illustrated [in this gist](https://gist.github.com/zkamvar/87e0730e55454156554c47283dd5ee37). 

In short, I **[found a solution](https://github.com/zkamvar/pkgdown/tree/znk-update-pandoc-markdown) and would like to submit a PR.** Read on for a few reprexes that illustrate the problem and solution.

## Problem 

With the current version of {pkgdown}, divs are collapsed:

``` r
remotes::install_github("r-lib/pkgdown@eae56f0")
library("pkgdown")
library("usethis")
library("xml2")

tmp <- tempfile()
create_package(path = tmp, check_name = FALSE, roxygen = FALSE, open = FALSE)
cat("# Test", file = file.path(tmp, "README.md"))
cat('# Test
### level 3
<div class="boo">

## level2

</div>
', file = file.path(tmp, "classy.md"))
pkgdown::init_site(tmp)
x <- read_html(file.path(tmp, "docs", "classy.html"))
xml_find_all(x, ".//div[contains(@class, 'boo')]")
#> {xml_nodeset (1)}
#> [1] <div class="boo">\n</div>
```

It's also worth noting that this engine does not appear to process the fenced divs either:

<details>
<summary>Unprocessed Fenced Divs</summary>

``` r
remotes::install_github("r-lib/pkgdown@eae56f0")
library("pkgdown")
library("usethis")
library("xml2")

tmp <- tempfile()
create_package(path = tmp, check_name = FALSE, roxygen = FALSE, open = FALSE)
cat("# Test", file = file.path(tmp, "README.md"))
cat('# Test
### level 3

::: boo

## level2

:::
', file = file.path(tmp, "classy.md"))
pkgdown::init_site(tmp)
x <- read_html(file.path(tmp, "docs", "classy.html"))
xml_find_all(x, ".//div[contains(@class, 'boo')]")
#> {xml_nodeset (0)}
xml_text(x) # fenced divs unprocessed :'(
#> [1] "Test • file79b649068d68\n    \n      \n  \n    \n      \n        Toggle navigation\n        \n        \n        \n      \n      \n        file79b649068d68\n        0.0.0.9000\n      \n    \n\n    \n      \n  \n    \n     \n  \n\n\n  Reference\n\n      \n  \n\n\n      \n\n      \n  \n    \n      Test\n    \n\n\n\n\n\nlevel 3\n::: boo\n\n\n\nlevel2\n:::\n\n\n\n  \n\n  \n    Contents\n    \n\n\n\n\n\n      \n  Developed by First Last.\n\n\n\n  Site built with pkgdown 1.5.1.9000.\n\n\n      \n\n  \n\n\n  "
```

<sup>Created on 2020-08-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

</details>

## Solution: use pandoc's `markdown` engine

**I would like to submit a PR for this change if one of the maintainers agrees that it is cromulent.**

I've created a fork of the repo and was able to fix this issue using `markdown` with the `markdown_github` options. There was initially the same issues that #1195 ran into, but i was able to fix them [using xpath manipulation](https://github.com/zkamvar/pkgdown/commit/1d2ece4c83de172c4e4e20dc83764273210f6e18#diff-909e6449ff4d4db377f6bfb40c34d7bb). The branch is here: https://github.com/zkamvar/pkgdown/tree/05175508ac8cef1b9d20755497bc1ce718aa2160 with a reprex:

``` r
remotes::install_github("zkamvar/pkgdown@05175508")
library("pkgdown")
library("usethis")
library("xml2")

tmp <- tempfile()
create_package(path = tmp, check_name = FALSE, roxygen = FALSE, open = FALSE)
cat("# Test", file = file.path(tmp, "README.md"))
cat('# Test
### level 3
<div class="boo">

## level2

</div>
', file = file.path(tmp, "classy.md"))
pkgdown::init_site(tmp)
pkgdown::build_home(tmp, preview = FALSE)
x <- read_html(file.path(tmp, "docs", "classy.html"))
xml_find_all(x, ".//div[contains(@class, 'boo')]")
#> {xml_nodeset (1)}
#> [1] <div id="level2" class="section level2 boo">\n<h2 class="hasAnchor">\n<a  ...
```

<sup>Created on 2020-08-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>
<summary>Fenced Divs are processed :)</summary>

``` r
# remotes::install_github("r-lib/pkgdown@eae56f0")
remotes::install_github("zkamvar/pkgdown@05175508")
library("pkgdown")
library("usethis")
library("xml2")

tmp <- tempfile()
create_package(path = tmp, check_name = FALSE, roxygen = FALSE, open = FALSE)
cat("# Test", file = file.path(tmp, "README.md"))
cat('# Test
### level 3

::: boo

## level2

:::
', file = file.path(tmp, "classy.md"))
pkgdown::init_site(tmp)
pkgdown::build_home(tmp, preview = FALSE, quiet = TRUE)
x <- read_html(file.path(tmp, "docs", "classy.html"))
xml_find_all(x, ".//div[contains(@class, 'boo')]") # Fenced divs processed :)
#> {xml_nodeset (1)}
#> [1] <div id="level2" class="section level2 boo">\n<h2 class="hasAnchor">\n<a  ...
```

<sup>Created on 2020-08-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

</details>

**Comment by hadley** [comment]
@zkamvar can you please file a new issue?
