### ISSUE TITLE
Explore netlify + travis build process

### ISSUE THREAD

**Issue by hadley** [r-lib/pkgdown#428]
So the site is automatically updated (and previewable) from pulls.

Should also make it possible to have per-branch sites

**Comment by jayhesselberth** [comment]
A slightly easier approach that doesn't involve travis is to expect PRs to include the updated website and then use netlify to display the updated site. You can set up hooks so that netlify inserts a unique URL into the PR comments that links to the new site for easy previewing.

**Comment by hadley** [comment]
That's easier for me, but harder for contributors.

**Comment by maxheld83** [comment]
I was looking into this a while back (August 2017), and while Netlify offers great branch/pull support for stuff that *Netlify* can compile from the respective github ref, it's not elegantly possible when Travis has to do the building, because the existing CLI tools (August 2017) do not allow *Travis* to do a "branch/pull deploy" on Netlify.
It would appear that to get this done, you'd need one of two things:

1. Support via the [`netlifyctl`](https://github.com/netlify/netlifyctl) CLI tool, that would allow us to pass `$TRAVIS_BRANCH` down to Netlify. (Though this would still require some `.travis.yml`-magic).
2. A dedicated [Travis deployment provider for netlify](https://docs.travis-ci.com/user/deployment/) that does this kind of thing natively. 

Since neither existed, I ended up just hardcoding a bunch of branches and deploy targets into my `.travis.yml`, but it's a pain.

Of course, as long as people have travis deploy to github's `/docs` (or whatever), as @yihui recommended, there's no problem. 
But even *more* compiled stuff on the repo (aside from `roxygen2`, ehem :)) would just drive me crazy.

Anyway, I had some email exchange with Travis and Netlify about this back in August, let me know if you'd like the details. They had some suggestions as to how this might be done (Travis deployment provider).

**Comment by hadley** [comment]
@maxheld83 ah that's a bummer. I was hoping that a branch based deployment might make it possible to have separate dev and CRAN package websites.

**Comment by maxheld83** [comment]
speaking of which (CI/CD), somewhat offtopic: Is there any chance RStudio might offer an integrated CI/CD product? (~ RStudio Connect + Git(hub) integration?)

It's a huge time sink to wrangle all these service providers (Netlify, Github, Travis, Shinyapps, local machine ...), and I'd be willing to pay good money for an RStudio-maintained CI/CD.

**Comment by hadley** [comment]
I'm going to close because it seems like netlify support is still lacking. I'll reopen if that ever changes. In the mean-time, it's also possible to use tic: https://github.com/krlmlr/tic.package

@maxheld83 not in the near to medium term, sorry

**Comment by jayhesselberth** [comment]
This article helps with CI, but still no netlify.

https://www.r-bloggers.com/continuous-deployment-of-package-documentation-with-pkgdown-and-travis-ci/
