### ISSUE TITLE
Default figure options

### ISSUE THREAD

**Issue by topepo** [r-lib/pkgdown#563]
I'd specifically like to be able to specify graphics or device options (e.g. transparent backgrounds, svg graphics) that would affect code chunks created by examples. This could be done in the example code, but it would be better to keep the formatting code separate, especially if it will be globally set for the package.

**Comment by hadley** [comment]
You want these options to affect both examples and articles? Can you give me the full set of options I might want to consider? (Or at least tell me where to look for that list?)

(BTW I think as rule figures with transparent backgrounds are bad practice because the foreground colours assume a backgorund colour, so you might as well actually save that in the file. That makes it easier to embed images in slides, tweet, etc.)

**Comment by topepo** [comment]
I see your point about the background but still think that this is a worthwhile feature for the examples and the articles. 

I usually modify `dev.args` and `dev` (when a `ggplot` theme isn't used).

**Comment by hadley** [comment]
I think we want to be able to set:

* `dev`, `dev.args`, `fig.ext`
* `fig.width`, `fig.height`, `fig.asp`, `fig.retina`

We'll need to pass those along to the vignettes and `README.Rmd`, and recreate their impact in `replay_html.recordedplot()`.

**Comment by hadley** [comment]
One challenge is that there's currently no standard way to pass knitr options into `rmarkdown::render()`, although I can override the settings in  `format$knitr$opts_chunk`.

**Comment by hadley** [comment]
Also need to think about what the `_pkgdown.yml` structure should look like:

```yaml
figure:
  dev: "svglite::svglite::svglite"
  fig.ext: "svg"
  dev.args: 
    pointsize: 12
```

Is `figure` the right top level name?

**Comment by hadley** [comment]
I'm going to go with figures for now.  Next steps:

* [ ] use metadata in `fig_save()` (or whatever calls it)
* [ ] add metadata to chunk options in `build_rmarkdown_format()`
* [ ] document in `build_reference()` and `build_articles()`
