### ISSUE TITLE
docsearch config JSON not in best format for Algolia

### ISSUE THREAD

**Issue by StevenMMortimer** [r-lib/pkgdown#637]
Thanks to @jayhesselberth for all the work on docsearch functionality. Below are a few things from my experience using it and submitting my config JSON to Algolia. I think it would be a nice gesture to the Algolia folks to ensure pkgdown creates JSON that best matches their specifications so they don't get overwhelmed with a bunch of JSON configs that aren't exactly what they want. 

Small changes that needed to be made: 

 * Algolia asked that I keep `sitemap_urls` as an array even when I only had one element
 * Algolia also added back some elements (e.g. `nb_hits` and `conversation_id`) that `build_docsearch_json()` neglected to keep from the original JSON config they created for my site
 * `build_docsearch_json()` created a file called `"docsearch.json"`, but that is not unique to my package so I had to change the file name to `"my-package-name.json"` when I submitted the pull request. It would be nice to figure out the package name and then give it a `.json` extension for the docsearch file.

Here is the difference between what pkgdown created and what Algolia changed on their end: 
https://github.com/algolia/docsearch-configs/commit/3e8ea55bfadc6ed667801e3380a915c3773aa16f

Here is the pull request from my experience pull requesting the pkgdown config JSON: https://github.com/algolia/docsearch-configs/pull/389

**Comment by jayhesselberth** [comment]
Did you build with the most recent pkgdown? The `docsearch.json` file is rendered with a template so it should be an array. It is in the [most recent build](https://github.com/r-lib/pkgdown/blob/master/docs/docsearch.json#L32-L34).

The `nb_hits` fields is created by the index build process, so that is independent of pkgdown. We could keep track of `conversation_id` but that seems unnecessary.

I agree the name of the JSON file could be `packagename.json`.
