### ISSUE TITLE
Standalone html files are not used anymore

### ISSUE THREAD

**Issue by pat-s** [r-lib/pkgdown#644]
We have some backups of older documentation versions stored in sub-folders using the `.html` files only.

Since a few weeks (maybe due to the release/dev changes?) the standalone html files are not picked up anymore and not copied to `docs/`. 

As these files are not changing anymore, there is no need to rebuild them. 

Would it be possible to also copy any `.html` files found under `vignettes` to `docs/` as it was before?

(PS: Congratulations to the first release!)

**Comment by privefl** [comment]
+1
it was super useful for long vignettes to knit.

**Comment by hadley** [comment]
Unfortunately you were depending on an incidental feature of pkgdown, not something that was included by design. Even if the files might not be changing any more, presumably your package is, so re-running is still important.

If you want to cache completely static versions, I'd recommend rendering to `.md` then renaming to `.Rmd`.

**Comment by privefl** [comment]
Would you accept a function that takes all the .html files in one directory and put them in the docs/articles/ directory?
I could make a PR.

**Comment by hadley** [comment]
Unforunately I don't think it's a good idea.
