### ISSUE TITLE
pkgdown fails to build an article with two .bib entries

### ISSUE THREAD

**Issue by jackwasey** [r-lib/pkgdown#657]
I have two valid bibtex files, which build fine with a vignette with YAML header like:
```
bibliography:
  - one.bib
  - two.bib
```

`pkgdown` will only build the corresponding article if _either_ of the bib files is present, but fails with pandoc-citepro error 83 when both are present, stating that one.bib is not found if both are present.

Concatenating one.bib and two.bib into all.bib makes it work fine. Could this be related to #658, in that if only one YAML entry is expected, the YAML is misinterpreted.

**Comment by Enchufa2** [comment]
Regarding #658, `pkgdown` expects more than one entry, but only the first one is used, as I explained there.

This is a completely different issue, because `pkgdown` does not read that entry. I believe that this is a bug in `rmarkdown` and the way it manages the `intermediates_dir` (see rstudio/rmarkdown#1300). In fact, if [this line](https://github.com/r-lib/pkgdown/blob/bfbf38c443ef2dafc17b9255d7b5db9d05dfb537/R/rmarkdown.R#L20) is commented out, the compilation succeeds. I still see an error though, but it is due to [this line](https://github.com/r-lib/pkgdown/blob/bfbf38c443ef2dafc17b9255d7b5db9d05dfb537/R/rmarkdown.R#L48) (again, from `rmarkdown`), which is not essential for PDFs.

I think that `pkgdown` should stop using the `intermediates_dir` feature from `rmarkdown`, because it contributes nothing and it's a long-standing broken option (and @yihui recommends against using it, e.g., [here](https://github.com/rstudio/rmarkdown/issues/1190#issuecomment-343612411)).

**Comment by hadley** [comment]
`rmarkdown::find_external_resources()` appears to error if `bibliography` contains more than one entry; this suggests the problem needs to be fixed in rmarkdown, not here.

(I agree that the use of `intermediates_dir` is suboptimal, but it's the least-worst solution that I could come up with)
