### ISSUE TITLE
pkgdown site should be in "development" development mode, not "unreleased"

### ISSUE THREAD

**Issue by jennybc** [r-lib/pkgdown#681]

**Comment by jayhesselberth** [comment]
If you put it in `devel` mode, all docs are written `docs/dev`.

**Comment by jennybc** [comment]
I know. Is that not desirable? I'm thinking through this myself as usethis ramps up for a release. It seems like the main site should reflect the current CRAN release. And the dev site should be tracking the dev version. This appears to be achievable but there's no easy way to toggle between then two, i.e. a drop-down menu or obvious crosslink. I just happen to know how to modify the URL.

I think we still haven't figured out exactly how this is going to work?

**Comment by jennybc** [comment]
I am in the midst of trying this for usethis:

  * check out a branch at most recent CRAN release
  * remake the site with modern pkgdown
  * merge the state of `docs/` into current master
  * *ideally I would have done all of the above right before bumping version last time*
  * put pkgdown in usethis into "development" mode and develop the new site in tandem with the package itself, on the way to next release

Thoughts?

**Comment by jennybc** [comment]
Here's the above in action:

The main site corresponds to the state of usethis at most recent CRAN release, v1.3.0:

http://usethis.r-lib.org/index.html

If you know to insert "dev" after "http://usethis.r-lib.org", you can see the site developing along with the dev version of usethis:

http://usethis.r-lib.org/dev/index.html

**Comment by jayhesselberth** [comment]
I like the idea of changing the version badge to a selector for the docs version, if more than one version exists.

readthedocs does something like this (see lower right button on https://bedtools.readthedocs.io/en/latest/)

**Comment by jennybc** [comment]
> I like the idea of changing the version badge to a selector for the docs version, if more than one version exists.

Yeah, I agree some way to move between them makes sense.

**Comment by batpigandme** [comment]
Just to add a real world example for the utility of what you've proposed, Jenny, this came up in community re. a "dev" ggplot2 geom:
https://community.rstudio.com/t/is-stat-qq-line-in-ggplot2-2-2-1-cran-latest/8983

**Comment by jayhesselberth** [comment]
Once we have the ability to easily go between stable and dev versions, would also be nice to see a message like "there's a new version of this function in the dev docs" if e.g. a function has changed between two versions.

**Comment by jayhesselberth** [comment]
I have been thinking about this and am struggling to see how having coexisting docs works in practice. The workflow described above "check out a branch" feels clunky and I think requires one to pay too close attention to which branch you're on, when to merge etc.

I wonder if pkgdown could accept git tags to build documentation from. These would be considered the "stable" docs (because they have been tagged, i.e. released), and then current master would be the dev version.

So a `_pkgdown.yml` could contain:

```yaml
docs:
  tags:
  - master # default, built under docs/dev
  - v1.0.0 # stable release,  built under docs/tags/v1.0.0
```

Then pkgdown would check out a tag, build it under `docs/dev/tag` and create a link to it (within the badge, which would turn into a dropdown menu with items colored by dev status).

This assumes a certain development workflow using git and release tags, but it is well documented and would encourage standardization.

**Comment by hadley** [comment]
I think it should be in `mode: auto` so we can dog-food the process.

I'm not sure whether or not we should continue to check in `docs/` so we see the changes to the rendering in pull requests. Regardless, we should probably adopt the new automatic build workflow in order to ensure that the published site is always up to date.
