### ISSUE TITLE
Navbar highlighting is seemingly random in individual reference pages

### ISSUE THREAD

**Issue by ArtemSokolov** [r-lib/pkgdown#777]
Dear developers,

What controls which element is highlighted in the navbar when a user navigates individual Reference pages? Taking a look at `pkgdown` itself, the [Reference index](https://pkgdown.r-lib.org/reference/index.html) correctly highlights "Reference" in the navbar. However, [individual reference pages](https://pkgdown.r-lib.org/reference/init_site.html) highlight the home button.

Looking at other packages, we find that [reference pages](https://aloy.github.io/qqplotr/reference/stat_pp_point.html) in `qqplotr` highlight "Articles". [Reference pages](https://artemsokolov.github.io/ABCmonster/reference/ABCcv.html) in my own package that I'm currently putting together seem to highlight yet another (custom) element called "Data".

This behavior appears somewhat arbitrary. Am I just missing an option somewhere? If not, I think the logical default behavior is to have individual reference pages continue highlighting "Reference" in the navbar.

Best,
-Artem

**Comment by hrecht** [comment]
Hi pkgdown team, I have noticed this same issue as well - individual function reference pages highlight the next tab over in the navbar, not the Reference tab. An example from my package: on each function reference page, the first vignette tab is highlighted. 

<img width="787" alt="screen shot 2018-08-23 at 8 29 55 pm" src="https://user-images.githubusercontent.com/9753760/44558643-58c01280-a713-11e8-999f-d3ad044595ac.png">

source: https://hrecht.github.io/censusapi/reference/getCensus.html

Is there a yaml option or something we could use that would solve this?

**Comment by hadley** [comment]
This is a bug; I don't think it would make sense to have an option that randomly highlights the incorrect navbar item.

**Comment by hadley** [comment]
I think the problem is that I've never attempted to spell out exactly what the criteria for selection is, and hence my javascript keeps hitting edge cases. I also don't know how to unit test javascript code.

I think the logic is something like this:

* Find all navigation links whose path is a prefix of the current path
* If there is exactly one, the problem is solved.
* If there is more than one, pick the one with the longest path. If the lengths are equal, pick the left most.

As far as I can tell, that corresponds to the code https://github.com/r-lib/pkgdown/blob/master/inst/assets/pkgdown.js#L21-L35. 

Oh hmmm, maybe I just have the arguments to `prefix_length(cur_path, path)` around the wrong way?

**Comment by hadley** [comment]
Hmmm, that seems to fix the problem, at least locally.

**Comment by hadley** [comment]
And fixed in the  dev version of the site: https://pkgdown.r-lib.org/dev/reference/init_site.html
