### ISSUE TITLE
Building site in parallel

### ISSUE THREAD

**Issue by KasperSkytte** [r-lib/pkgdown#805]
I see this has been given a shot previously (#744 and #745), but I still want to give a huge (but still `n=1`, unfortunately) vote for trying to implement parallelization in one way or the other for all `build_*` functions. 
I often have to wait ~15-20 mins for all pages to be rendered, and as the pages are rendered independently, it must be well suited for parallelization with a big speed increase?

**Comment by hadley** [comment]
I think this will need #718 first — then every example and every vignette could be built in a separate process, run in parallel.

**Comment by hadley** [comment]
Thanks for filing this issue! Unfortunately, I don't we're likely to implement it — it's been open for ~3 years, and there continue to be items with higher priority on our to do list. It's our policy to close such issues to help stay focussed on the biggest problems, but the issue is still indexed by google, so if other people hit it, they'll be able to find it, and we can consider reopen it if it turns out to be a common need. Thanks for reporting and I'm sorry we couldn't help more 😞.

**Comment by KasperSkytte** [comment]
Hi Hadley

I understand. Nowadays, GitHub actions will render the website anyways, so it's not a big deal anymore, at least for me.
