### ISSUE TITLE
Support bookdown

### ISSUE THREAD

**Issue by hadley** [r-lib/pkgdown#853]
While writing a bunch of rich interlinked vignettes for vctrs, it made me wish I could write in bookdown instead. There would be a number of advantages to writing a book instead of vignettes:

* Built in linear flow
* Easier to link between pages
* Wouldn't bundle in package so don't need to worry about file size

I think it would be _relatively_ easy to support package "book" from pkgdown:

* We adopt a convention for the directory a bookdown site should live in (and provide a usethis helper to create the basic structure)

* We'd need to re-theme the output, probably by using the same approach we already do for Rmarkdown. Alternatively, we might need a completely new theme to replace gitbook.

* We'd add a new heading to the nav bar which would list all h1s from the book (and maybe, optionally, the h2s?)

**Comment by DougManuel** [comment]
We've talked about this in our group. Interesting to note when you (@hadley) use different documentation. For R packages you already have a pkgdown for devtools, and a [bookdown](https://github.com/hadley/r-pkgs)
There are quite a few 'vignettes' (literal meaning) in your book, but of course, they are complementary package vignettes.

Then there are additional venues for documentation and vignettes. Yihui Xie and others like blogdown for introducing and providing 'vignettes', such as for [formatR](https://yihui.name/formatr/). If we did a count, probably most vignettes are in simple notebooks (rMarkdown or Jupyter). Vignettes are also in cheatsheets. 

This rich and fun documentation ecosystem works very well.

**Comment by maxheld83** [comment]
I think this would be great, and would let pkgdown support the kind of long-form/linear documentation such as the (amazing) [docker guides](https://docs.docker.com/develop/dev-best-practices/).

<img width="2549" alt="docker" src="https://user-images.githubusercontent.com/5372770/81729482-51fba500-948c-11ea-83ab-db2cb3505ebb.png">


What I really like about those docs in particular is how they allow me to navigate on the left *and* right:
- on the left is a vertical navbar to navigate between documents/sites (what, in the R world, might be separate articles/vignettes)
- on the right is a vertical navbar to navigate within a document (between headings).

This might seem like a small thing, but I think having that in one view is crucial.
I noticed how I am otherwise often confused, wondering whether some section I am looking for is a heading or a separate document, and I easily loose my focus while figuring that out.

It's also just a really nice, soothing way to make sure you *read it all*.

I recently noticed that RStudio has been using the same style for their on-prem product docs, which used to be bookdowns (or at least gitbooks) (here, [RSPM](https://docs.rstudio.com/rspm/admin/getting-started/configuration/):

<img width="2553" alt="rspm" src="https://user-images.githubusercontent.com/5372770/81729597-87a08e00-948c-11ea-9bfc-c9c9b3c61037.png">

I believe the RSPM docs are based [mkdocs-material](https://squidfunk.github.io/mkdocs-material/) which in turn is based on [mkdocs](https://github.com/mkdocs/mkdocs).

Doesn't mean that either of those CSSs would jibe with the rest of pkgdown, they probably won't. (Though there are some bootswatch/bootstrap-based mkdocs themes).

**Comment by maxheld83** [comment]
Just noticed that gitbook has a [new two-navbar theme out](https://docs.gitbook.com), and there's an issue tracked on bookdown to update to it https://github.com/rstudio/bookdown/issues/670

**Comment by maelle** [comment]
@maxheld83 you might like https://github.com/alex-shpak/hugo-book (it has the TOC on the right) -- not for pkgdown since it's not Hugo based. :-)

**Comment by Robinlovelace** [comment]
Big +1 from me. I'm not sure if this has already been solved but a related issue is that vignettes don't seem to respect `\@ref()` references to Figures and Tables, even with output: bookdown::html_vignette2.

An example of this can be found here: https://saferactive.github.io/trafficalmr/articles/report1.html#data-collection-and-cleaning-1

Related question: is there currently any way to make

`Table @ref(tab:tctab)` 

Become Table 1 with pkgdown?

**Comment by jayhesselberth** [comment]
@Robinlovelace you might try installing https://github.com/r-lib/pkgdown/pull/1352 to see if that fixes cross-references.

**Comment by Robinlovelace** [comment]
Thanks @jayhesselberth, see commit above. Let's see if that fixes it.

**Comment by Robinlovelace** [comment]
The deploy seems to have worked with that branch. See result here: https://saferactive.github.io/trafficalmr/articles/report1.html#obtaining-traffic-calming-interventions-from-osm

**Comment by Robinlovelace** [comment]
I don't see the issue fixed though...

**Comment by jayhesselberth** [comment]
You might need to add this to your vignette header as well:

```yaml
pkgdown:
  as_is: true
  set_null_theme: false
```

**Comment by Robinlovelace** [comment]
Aha, many thanks.

**Comment by Robinlovelace** [comment]
Is there a way to set that globally?

**Comment by Robinlovelace** [comment]
See commit above that adds that incantation to the vignette yaml header.

**Comment by Robinlovelace** [comment]
Good news @jayhesselberth, it works :tada: https://saferactive.github.io/trafficalmr/articles/report1.html#obtaining-traffic-calming-interventions-from-osm

Many thanks for seeing the 'link' (get it ; ) and thanks to @GegznaV for making it work.

**Comment by hadley** [comment]
Closing this since it seems unlikely that we'll have the development time to implement in the near future. We'll definitely keep thinking about better ways to integrate package document and books.
