### ISSUE TITLE
Release pkgdown 1.2

### ISSUE THREAD

**Issue by hadley** [r-lib/pkgdown#906]
Prepare for release:

* [x] `devtools::check_win_devel()`
* [x] `rhub::check_for_cran()`
* [x] `revdepcheck::revdep_check(num_workers = 4)`
* [x] [Polish NEWS](http://style.tidyverse.org/news.html#before-release)

Perform release:

* [x] Bump version (in DESCRIPTION and NEWS)
* [x] `devtools::check_win_devel()` (again!)
* [x] `devtools::submit_cran()`
* [x] `pkgdown::build_site()`
* [x] Approve email

Wait for CRAN...

* [x] Tag release
* [x] Bump dev version
* [ ] Write blog post
* [ ] Tweet

Template from <https://github.com/r-lib/usethis/issues/338>

**Comment by hadley** [comment]
@jayhesselberth everything looks good from my end. Do you see any reason that I shouldn't go ahead and submit to CRAN?

**Comment by jayhesselberth** [comment]
Looks good, go for it.

**Comment by jayhesselberth** [comment]
FYI the travis build that would have deployed the version 1.2.0 build at the main site was cancelled, I think because you quickly made the next commit that incremented version number. So now the dev site is correct, but the "released" site is still the old version number (1.1.0.9000).

I restarted the travis build for the preceding commit, which should hopefully update the main site.

I think there is a travis option that prevents cancelling of successive commits. Or you could just wait a few minutes before updating the version number.

**Comment by hadley** [comment]
Oh I didn’t think about that. Although I have a vague memory that a release also kicks off a build?

**Comment by hadley** [comment]
We'll do the blog post after 1.2.1 is on its way to CRAN
