### ISSUE TITLE
vignette chunk settings

### ISSUE THREAD

**Issue by luca-scr** [r-lib/pkgdown#920]
In package vignettes I usually set some defaults for chunks, such as:
```{r}
opts_chunk$set(fig.align = "center", 
               out.width = "90%",
               fig.width = 6, fig.height = 5.5)
```
These defaults are respected when the package is created, but they are not obeyed when the vignette is prepared for inclusion on the web page using **pkgdown**.

**Comment by jayhesselberth** [comment]
You can update site-wide figure settings in the [yaml config](https://pkgdown.r-lib.org/reference/build_articles.html#figures).

**Comment by jayhesselberth** [comment]
I'm surprised this doesn't have an effect on vignettes as it's documented in the `build_articles()` section. Can you generate [a reprex](https://github.com/r-lib/pkgdown/blob/master/.github/CONTRIBUTING.md#package-reprexes)?

**Comment by luca-scr** [comment]
You may find at this link https://www.dropbox.com/s/novinalqxo6w4cr/test.zip?dl=0 a simple reproducible example of an R package with website and vignette created using pkgdown::build_site()
This example shows the problem with graphs size: see the example in help(fun) and in vignette.
Thanks.

**Comment by Freguglia** [comment]
I was facing the same issue when setting figure sizes with `fig.width` and `fig.height`, but using `out.width` **only** caused the figure sizes to respect the chunk option in the `pkgdown` site. 

An example is in this `ggplot2` [vignette](https://github.com/tidyverse/ggplot2/blob/master/vignettes/ggplot2-specs.Rmd), which results in this pkgdown article: https://ggplot2.tidyverse.org/articles/ggplot2-specs.html#line-endjoin-paramters. 

Since this seems not fixed yet, using `out.width` instead of `fig.width` seems to work right now.

**Comment by hadley** [comment]
I think this is fixed. The ggplot2 vignette looks fine to me, as did the simple reprex below:

````
---
title: "Output Rendering"
---

```{r include = FALSE}
knitr::opts_chunk$set(collapse = TRUE, comment = "#>")
```

This vignette tests pkgdown output rendering for several use cases.

```{r}
plot(1:10)
```

```{r, out.width = "25%"}
plot(1:10)
```

```{r}
knitr::opts_chunk$set(out.width = "25%")
```

```{r}
plot(1:10)
```

````
