### ISSUE TITLE
More control over Opengraph/twitter card

### ISSUE THREAD

**Issue by thomasp85** [r-lib/pkgdown#936]
The automatic generation of og/twitter card metadata is nice, but it would be great to be able to supply alternative default (and potentially page specific) pictures. The use of logo.png is suboptimal, as this file is best tightly cropped and with a transparent background when used in docs and readme, but this leads to poor look on twitter, where the optimal is a square, slightly padded image with white background.

An example of current look:
<img width="618" alt="screenshot 2018-12-18 at 09 08 43" src="https://user-images.githubusercontent.com/1775316/50140330-aa813f80-02a4-11e9-8e2a-e8ef5ab5a0c7.png">

**Comment by jayhesselberth** [comment]
This should be straightforward via params in `_pkgdown.yml`. A global setting is easy, per-page is harder.

``` yaml
template:
  opengraph:
    img: path/to/img
```

Change:

https://github.com/r-lib/pkgdown/blob/11facef9e1e52cd26bce76684a4835a32b7e35d2/R/render.r#L97

to, e.g. (need to handle the fig path):

``` r
og$image <- pkg$meta$opengraph$img %||% paste0(site_url, "logo.png")
```

**Comment by maelle** [comment]
@jayhesselberth Interested in a PR at least for the global option?

Regarding the page-specific images, can one add such an argument to the vignette YAML header? And then tweak the code somewhere near https://github.com/r-lib/pkgdown/blob/04e3f6ee259b17bed7246f237652e4ba7d6742d4/R/build-articles.R#L180?

@thomasp85 what would you use as an image for `gganimate` instead of the hex logo? A square logo, or a padded version of the hex with a white background? If the latter is a good default, I wonder where a function helping make and save the padded version (like `usethis::use_logo()`) could live.

**Comment by thomasp85** [comment]
I’d use a padded version over white background

**Comment by maelle** [comment]
So would a function producing that version, and saving it at the right location (maybe man/figures/og-logo.png), make any sense anywhere? Then `pkgdown` could use, by order of priority,
* the logo path indicated in _pkgdown.yml
* og-logo.png if it exists,
* logo.png otherwise if it exists,
* nothing :-)

**Comment by thomasp85** [comment]
My dream scenario would be that pkgdown did the padding automatically - the requirements for OpenGraph is so different from what is expected from logo.png, that it will only be by chance that it can be used unmodified in OpenGraph...

But in the lack of such automation I'd like what you propose...

**Comment by maelle** [comment]
> My dream scenario would be that pkgdown did the padding automatically - the requirements for OpenGraph is so different from what is expected from logo.png, that it will only be by chance that it can be used unmodified in OpenGraph...

From what I've seen in the history of this repo the dependency on `magick` was [dropped](https://github.com/r-lib/pkgdown/blob/83f2afb5d2ec85abe29bfd8d67408cdf2bb55f03/NEWS.md#new-features) though, so I'm not sure doing the conversion here is feasible?

@jayhesselberth & others in charge, are you interested in a PR such that `pkgdown` could use, by order of priority,

*  the logo path indicated in _pkgdown.yml
* og-logo.png if it exists,
* logo.png otherwise if it exists,
* nothing :-) ? 

And maybe a different PR after that to try and make it possible to set per page for articles?

And regarding a helper function that'd pad logo.png+add a white background (using `magick`), where could it be added? If not here, I could ask over in `usethis` repo. If not welcome there either, I'm not too sure where it should live.
