### ISSUE TITLE
lazy=TRUE not working in deploy_site_github

### ISSUE THREAD

**Issue by thomasp85** [r-lib/pkgdown#937]
As lazy building works by inspecting the mtime metadata of source and destination files it has no effect when deploying from github, as git doesn't store file metadata. Having a functioning lazy deploy would be great for pages with a lot of complex rendered documentation...

Is it possible to move away from using mtime and use e.g. file hashes in the same way as being done by roxygen2?

**Comment by jayhesselberth** [comment]
pkgdown checks whether the Rd file is newer than its HTML output. If it is and `lazy = TRUE`, the HTML will be rebuilt. I don't see how to use hashes here, as the hash of an Rd file and its HTML output will always be different.

If `skip_cleanup` is used in the travis build, I wonder whether `deploy_site_github()` could be modified to detect whether there is a previous checkout (from a previous build) into which new content could be pulled. The travis file system presumably keeps mtime information, so then `lazy = TRUE` should have the intended effect.

**Comment by thomasp85** [comment]
The problem is that the html files will never be older than the source files due to git clone updating last-modified time...

My idea with hashes was to write the hash of the source as a comment at the top of the html file and then compare that when determining if something has changed

**Comment by jayhesselberth** [comment]
> write the hash of the source as a comment at the top of the html file 

This should work and would be more robust than mtime.

**Comment by hadley** [comment]
My sense is that this will be a lot of work in order to fix a problem that I _think_ can be solved elsewhere, as part of a re-consideration of how most github pkgdown sites should be created.

**Comment by bmreiniger** [comment]
What about just relaxing the mtime comparison, e.g. adding 1 (second) to the target's mtime?
https://github.com/r-lib/pkgdown/blob/04d3a76892320ac4bd918b39604c157e9f83507a/R/utils-fs.R#L61

(When cloning/pulling from github, local timestamps are often nearly-equal (particularly on the first clone, or when pulling a branch to inspect before merging).  Then the `lazy = TRUE` option fairly often will rebuild, presumably because the target is _slightly older_ than the source.)
